"""Common scaffolding for the GhostLM distillation pipeline.

The corpus problem at ghost-3B+ scale is documented in
``docs/hardware_pathway.md``: Chinchilla-optimal training of a 3B
model wants 60B tokens, the current GhostLM corpus is 363M, and the
remaining cybersec text on the public web is mostly tapped out. The
lever is synthetic data, generated by a strong teacher model from
the existing GhostLM corpus seeds.

This module is the shared plumbing for that synthesis:

  - ``call_provider`` dispatches to Ollama (local), Anthropic, or
    OpenAI-compatible APIs based on a uniform config.
  - ``DistillRecord`` is the pretrain-ready output schema (matches the
    fact-QA recipe so distilled records mix into ``train.jsonl``
    without a format change).
  - ``StreamingWriter`` + ``ResumeIndex`` give every distill script
    resume-safety: kill mid-run, re-run, pick up from the last
    completed source record.
  - ``content_dedup`` collapses near-identical generations
    (5-shingle Jaccard >= 0.9) so a teacher model that occasionally
    repeats itself doesn't bloat the corpus with copies of the same
    walkthrough.

Per-distill scripts (one per content type) live next to this file:
``distill_ctf_walkthroughs.py``, ``distill_threat_modeling.py``,
``distill_deobfuscation.py``, ``distill_malware_analysis.py``. Each
imports from this module, defines its own prompt template + source
selector, and writes to a typed output JSONL.
"""

from __future__ import annotations

import hashlib
import json
import os
import time
import urllib.error
import urllib.request
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable, Dict, Iterable, Iterator, List, Optional, Set, Tuple


# ---------------------------------------------------------------------------
# Provider dispatch
# ---------------------------------------------------------------------------


@dataclass
class ProviderConfig:
    """Generation backend selector. One of:

    - ``ollama`` (local Ollama daemon, free, used by the v0.9 fact-QA
      recipe). Set ``model`` to e.g. ``"qwen2.5:14b"``.
    - ``anthropic`` (Claude API, paid). Set ``model`` to e.g.
      ``"claude-sonnet-4-6"``. Reads ``ANTHROPIC_API_KEY`` from env.
    - ``openai`` (works for OpenAI proper, plus Together AI, Groq,
      Fireworks, OpenRouter, Mistral; anything that exposes
      ``/v1/chat/completions``). Set ``base_url`` per provider; reads
      ``OPENAI_API_KEY`` (or ``TOGETHER_API_KEY`` etc) from env via
      the explicit ``api_key_env`` field.
    """
    name: str
    model: str
    base_url: Optional[str] = None
    api_key_env: Optional[str] = None
    temperature: float = 0.4
    max_tokens: int = 2000
    timeout_sec: int = 240


def call_provider(cfg: ProviderConfig, prompt: str,
                  system: Optional[str] = None) -> Optional[str]:
    """Dispatch to the configured provider. Returns the generated text
    string, or None on any failure. Per-provider failure modes are
    swallowed and logged, never raised, because distill loops are
    designed to be resumable across thousands of records and one bad
    response per 1000 is normal."""
    try:
        if cfg.name == "ollama":
            return _call_ollama(cfg, prompt, system)
        if cfg.name == "anthropic":
            return _call_anthropic(cfg, prompt, system)
        if cfg.name == "openai":
            return _call_openai(cfg, prompt, system)
        raise ValueError(f"Unknown provider: {cfg.name}")
    except Exception as e:  # noqa: BLE001 - distill loops never crash on one record
        print(f"  provider error ({cfg.name}/{cfg.model}): {type(e).__name__}: {e}")
        return None


def _call_ollama(cfg: ProviderConfig, prompt: str, system: Optional[str]) -> Optional[str]:
    """Ollama's /api/generate endpoint. Same shape as the existing
    build_fact_qa_data.py recipe used in v0.8 / v0.9."""
    body = {
        "model": cfg.model,
        "prompt": (system + "\n\n" + prompt) if system else prompt,
        "stream": False,
        "options": {
            "temperature": cfg.temperature,
            "num_predict": cfg.max_tokens,
        },
    }
    url = (cfg.base_url or "http://localhost:11434") + "/api/generate"
    req = urllib.request.Request(
        url, data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=cfg.timeout_sec) as resp:
        data = json.loads(resp.read())
    return (data.get("response") or "").strip() or None


def _call_anthropic(cfg: ProviderConfig, prompt: str, system: Optional[str]) -> Optional[str]:
    """Anthropic Messages API. Used when distilling against Claude
    Sonnet/Opus; their security knowledge is currently the strongest
    of any closed model and the per-token cost is reasonable for
    medium-volume runs."""
    api_key = os.environ.get(cfg.api_key_env or "ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError(f"{cfg.api_key_env or 'ANTHROPIC_API_KEY'} not set")
    body = {
        "model": cfg.model,
        "max_tokens": cfg.max_tokens,
        "temperature": cfg.temperature,
        "messages": [{"role": "user", "content": prompt}],
    }
    if system:
        body["system"] = system
    url = (cfg.base_url or "https://api.anthropic.com") + "/v1/messages"
    req = urllib.request.Request(
        url, data=json.dumps(body).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
    )
    with urllib.request.urlopen(req, timeout=cfg.timeout_sec) as resp:
        data = json.loads(resp.read())
    blocks = data.get("content", [])
    if not blocks:
        return None
    return "".join(b.get("text", "") for b in blocks if b.get("type") == "text").strip() or None


def _call_openai(cfg: ProviderConfig, prompt: str, system: Optional[str]) -> Optional[str]:
    """OpenAI-compatible chat completions. Works for OpenAI proper plus
    Together AI / Groq / Fireworks / OpenRouter / Mistral; the
    distinction is just ``base_url`` and ``api_key_env``."""
    api_key = os.environ.get(cfg.api_key_env or "OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError(f"{cfg.api_key_env or 'OPENAI_API_KEY'} not set")
    msgs: List[Dict] = []
    if system:
        msgs.append({"role": "system", "content": system})
    msgs.append({"role": "user", "content": prompt})
    body = {
        "model": cfg.model,
        "messages": msgs,
        "temperature": cfg.temperature,
        "max_tokens": cfg.max_tokens,
    }
    url = (cfg.base_url or "https://api.openai.com") + "/v1/chat/completions"
    req = urllib.request.Request(
        url, data=json.dumps(body).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
    )
    with urllib.request.urlopen(req, timeout=cfg.timeout_sec) as resp:
        data = json.loads(resp.read())
    choices = data.get("choices", [])
    if not choices:
        return None
    return (choices[0].get("message", {}).get("content") or "").strip() or None


# ---------------------------------------------------------------------------
# Output schema
# ---------------------------------------------------------------------------


@dataclass
class DistillRecord:
    """One distilled record. Pretrain-ready: drops into train.jsonl as
    a single document with no further processing. The ``id`` field is
    deterministic (hash of source + prompt + content) so re-runs
    produce stable identifiers and resume logic works."""
    id: str
    source: str               # e.g. "distill_ctf"; used for source-mix weights at training time
    teacher: str              # provider/model that produced this record
    seed_source: str          # GhostLM corpus source the prompt was derived from (e.g. "mitre_attack")
    seed_id: str              # original record id in the seed source (e.g. "T1059")
    text: str                 # the generated content, ready to pretrain on

    @classmethod
    def make(cls, source: str, teacher: str, seed_source: str,
             seed_id: str, text: str) -> "DistillRecord":
        """Build a record with a deterministic content-hash id."""
        h = hashlib.sha1()
        h.update(f"{source}\n{teacher}\n{seed_source}\n{seed_id}\n{text}".encode("utf-8"))
        return cls(
            id=f"{source}#{seed_id}#{h.hexdigest()[:10]}",
            source=source,
            teacher=teacher,
            seed_source=seed_source,
            seed_id=seed_id,
            text=text,
        )


# ---------------------------------------------------------------------------
# Resume-safe streaming writer
# ---------------------------------------------------------------------------


class ResumeIndex:
    """Tracks which seed records have already been distilled so a
    re-run can skip them. Keyed by ``(seed_source, seed_id)`` since the
    same seed may appear in multiple distill output types simultaneously
    but each output file gets its own resume index."""

    def __init__(self, path: Path):
        self.path = path
        self.seen: Set[Tuple[str, str]] = set()
        if path.exists():
            for line in path.read_text(encoding="utf-8").splitlines():
                try:
                    rec = json.loads(line)
                    self.seen.add((rec.get("seed_source", ""), rec.get("seed_id", "")))
                except json.JSONDecodeError:
                    continue

    def already_done(self, seed_source: str, seed_id: str) -> bool:
        return (seed_source, seed_id) in self.seen


class StreamingWriter:
    """Append-only JSONL writer with explicit flush per record so a
    process kill mid-run loses at most one record."""

    def __init__(self, path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        self.path = path
        self.fh = path.open("a", encoding="utf-8")

    def write(self, record: DistillRecord) -> None:
        self.fh.write(json.dumps(asdict(record), ensure_ascii=False) + "\n")
        self.fh.flush()

    def close(self) -> None:
        self.fh.close()


# ---------------------------------------------------------------------------
# Quality filters
# ---------------------------------------------------------------------------


def _shingles(text: str, n: int = 5) -> Set[str]:
    """5-word shingle set used by content_dedup."""
    words = text.lower().split()
    if len(words) < n:
        return set()
    return {" ".join(words[i:i + n]) for i in range(len(words) - n + 1)}


def content_dedup(records: Iterable[DistillRecord],
                  jaccard_threshold: float = 0.9) -> Iterator[DistillRecord]:
    """Pass-through generator that drops records whose 5-shingle Jaccard
    similarity to a previously-yielded record exceeds the threshold.
    Catches the case where a teacher model generates near-identical
    walkthroughs for related but distinct seed records (e.g. T1059.001
    and T1059.003 both producing the same generic 'PowerShell is bad'
    write-up)."""
    seen_shingle_sets: List[Set[str]] = []
    for rec in records:
        sh = _shingles(rec.text)
        if not sh:
            yield rec
            continue
        is_dup = False
        for prev in seen_shingle_sets:
            inter = len(sh & prev)
            union = len(sh | prev)
            if union and (inter / union) >= jaccard_threshold:
                is_dup = True
                break
        if is_dup:
            continue
        seen_shingle_sets.append(sh)
        yield rec


def quality_ok(text: str, min_words: int = 80, max_words: int = 1500) -> bool:
    """Crude length-and-shape filter. Drops obvious failures:
    refusal-style replies, single-sentence stubs, runaway repetition.
    Per-distill scripts can layer their own type-specific filters on
    top (e.g. CTF walkthroughs require step numbering)."""
    words = text.split()
    if len(words) < min_words or len(words) > max_words:
        return False
    refusal_signals = (
        "i can't help with",
        "i cannot help",
        "i'm not able to",
        "i won't",
        "as an ai",
        "as a language model",
    )
    lower = text.lower()
    if any(sig in lower for sig in refusal_signals):
        return False
    # Catch runaway repetition: if any 8-word phrase appears 5+ times,
    # the teacher mode-collapsed; reject.
    if len(words) >= 40:
        eights = [" ".join(words[i:i + 8]) for i in range(len(words) - 7)]
        from collections import Counter
        most = Counter(eights).most_common(1)
        if most and most[0][1] >= 5:
            return False
    return True


# ---------------------------------------------------------------------------
# Source loaders (the seed records distill scripts pull from)
# ---------------------------------------------------------------------------


def load_jsonl_source(path: Path, id_field: str = "id",
                      text_field: str = "text") -> List[Dict[str, str]]:
    """Read a GhostLM corpus shard and return {seed_id, seed_text}
    rows. Used by every distill script; the per-script choice of which
    shard to seed from (mitre_attack, cwe, ctftime, exploitdb, ...)
    drives the kind of synthetic data you get."""
    out: List[Dict[str, str]] = []
    if not path.exists():
        return out
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not isinstance(rec, dict):
                continue
            sid = rec.get(id_field) or rec.get("ref") or rec.get("chunk_id") or ""
            stext = rec.get(text_field) or rec.get("content") or rec.get("body") or ""
            if sid and stext:
                out.append({"seed_id": str(sid), "seed_text": str(stext)})
    return out
