#!/usr/bin/env python3
"""Phase 4: append 40 more patterns to each of code-explain and code-write."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPLAIN = REPO_ROOT / "data" / "raw" / "code_explain_patterns.jsonl"
WRITE = REPO_ROOT / "data" / "raw" / "code_write_patterns.jsonl"


EXPLAIN_PATTERNS = [
    {"id": "CE-121", "language": "python", "snippet": "class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.end = False\n\nclass Trie:\n    def __init__(self):\n        self.root = TrieNode()\n    def insert(self, word):\n        node = self.root\n        for ch in word:\n            node = node.children.setdefault(ch, TrieNode())\n        node.end = True\n    def search(self, word):\n        node = self.root\n        for ch in word:\n            if ch not in node.children:\n                return False\n            node = node.children[ch]\n        return node.end", "purpose": "Trie (prefix tree) for word lookup", "explanation": "Each node has a dict of child characters; the .end flag marks complete words. Insert and search are both O(L) where L is the word length. Space is O(N*L) worst case but shares prefixes so dictionaries-of-English compress well. Used in autocomplete, spell-check, IP routing tables (radix trie variant).", "key_concepts": ["trie", "prefix sharing", "O(L) lookup"]},
    {"id": "CE-122", "language": "python", "snippet": "class SegTree:\n    def __init__(self, arr):\n        self.n = len(arr)\n        self.tree = [0] * (4 * self.n)\n        self._build(arr, 1, 0, self.n - 1)\n    def _build(self, arr, v, l, r):\n        if l == r:\n            self.tree[v] = arr[l]\n            return\n        mid = (l + r) // 2\n        self._build(arr, 2 * v, l, mid)\n        self._build(arr, 2 * v + 1, mid + 1, r)\n        self.tree[v] = self.tree[2 * v] + self.tree[2 * v + 1]", "purpose": "Segment tree for range-sum queries on a static array", "explanation": "Builds a binary tree where each node holds the sum over a contiguous range. Internal nodes have l..r range; leaves are single elements. O(n) build, O(log n) point-update + range-query. Space 4n is the safe upper bound. For mutable arrays, point updates walk leaf-to-root in O(log n). Variations: range-min, range-max, lazy propagation for range-update.", "key_concepts": ["segment tree", "range queries", "tree as array"]},
    {"id": "CE-123", "language": "python", "snippet": "def floyd_warshall(graph):\n    n = len(graph)\n    dist = [row[:] for row in graph]\n    for k in range(n):\n        for i in range(n):\n            for j in range(n):\n                if dist[i][k] + dist[k][j] < dist[i][j]:\n                    dist[i][j] = dist[i][k] + dist[k][j]\n    return dist", "purpose": "Floyd-Warshall all-pairs shortest paths", "explanation": "O(V^3) but tiny constants — three nested loops over the same range. dist[i][j] is updated to be the shortest path using nodes 0..k as intermediates. Initialise with infinity for non-edges and 0 on the diagonal. Detects negative cycles (any dist[i][i] < 0 after the loop). Beats Dijkstra-from-every-node when E ≈ V^2.", "key_concepts": ["all-pairs shortest paths", "dynamic programming on intermediate nodes"]},
    {"id": "CE-124", "language": "python", "snippet": "from heapq import heappush, heappop\n\ndef a_star(start, goal, neighbours, h):\n    open_set = [(h(start), 0, start)]\n    came_from = {}\n    g = {start: 0}\n    while open_set:\n        _, gx, x = heappop(open_set)\n        if x == goal:\n            return reconstruct(came_from, x)\n        for n, cost in neighbours(x):\n            new_g = gx + cost\n            if new_g < g.get(n, float('inf')):\n                g[n] = new_g\n                came_from[n] = x\n                heappush(open_set, (new_g + h(n), new_g, n))\n    return None", "purpose": "A* shortest path with a heuristic function", "explanation": "Like Dijkstra plus a heuristic h(x) estimating cost from x to goal. Heap ordered by g(x) + h(x). If h is admissible (never overestimates), A* finds the optimal path; if also consistent, no node is relaxed twice. Common in pathfinding (game AI), puzzle solvers (8-puzzle Manhattan-distance heuristic), routing.", "key_concepts": ["A* search", "heuristic-guided search", "admissible heuristic"]},
    {"id": "CE-125", "language": "python", "snippet": "def tarjan_scc(graph):\n    index = {}\n    lowlink = {}\n    on_stack = set()\n    stack = []\n    sccs = []\n    counter = [0]\n    def visit(u):\n        index[u] = lowlink[u] = counter[0]\n        counter[0] += 1\n        stack.append(u); on_stack.add(u)\n        for v in graph.get(u, []):\n            if v not in index:\n                visit(v)\n                lowlink[u] = min(lowlink[u], lowlink[v])\n            elif v in on_stack:\n                lowlink[u] = min(lowlink[u], index[v])\n        if lowlink[u] == index[u]:\n            comp = []\n            while True:\n                w = stack.pop(); on_stack.discard(w)\n                comp.append(w)\n                if w == u: break\n            sccs.append(comp)\n    for u in graph:\n        if u not in index: visit(u)\n    return sccs", "purpose": "Tarjan's strongly-connected components", "explanation": "Single DFS pass producing all SCCs in reverse-topological order. index is the DFS visit order; lowlink is the smallest index reachable from the subtree. When lowlink[u] == index[u], u is the root of an SCC and we pop the stack to form it. O(V + E). Used for: dependency-cycle detection, 2-SAT solving, condensation of digraphs.", "key_concepts": ["strongly connected components", "Tarjan's algorithm", "lowlink + DFS index"]},
    {"id": "CE-126", "language": "python", "snippet": "from abc import ABC, abstractmethod\n\nclass Visitor(ABC):\n    @abstractmethod\n    def visit_int(self, node): ...\n    @abstractmethod\n    def visit_str(self, node): ...\n\nclass IntNode:\n    def __init__(self, val): self.val = val\n    def accept(self, v): return v.visit_int(self)\n\nclass StrNode:\n    def __init__(self, val): self.val = val\n    def accept(self, v): return v.visit_str(self)", "purpose": "Visitor pattern: separate operations from data structures", "explanation": "Each node accepts a Visitor, dispatching to the visitor's type-specific method. Adding a new operation is a new Visitor class; adding a new node type requires touching every Visitor. Tradeoff: easy to add ops, hard to add types — opposite of regular polymorphism. Python's functools.singledispatch is a more pythonic alternative when you control the operation but not the types.", "key_concepts": ["visitor pattern", "double dispatch", "operations vs types tradeoff"]},
    {"id": "CE-127", "language": "python", "snippet": "class Command(ABC):\n    @abstractmethod\n    def execute(self): ...\n    @abstractmethod\n    def undo(self): ...\n\nclass DrawCommand(Command):\n    def __init__(self, canvas, shape):\n        self.canvas, self.shape = canvas, shape\n    def execute(self): self.canvas.add(self.shape)\n    def undo(self): self.canvas.remove(self.shape)\n\nclass History:\n    def __init__(self): self.commands = []\n    def do(self, cmd):\n        cmd.execute(); self.commands.append(cmd)\n    def undo(self):\n        if self.commands:\n            self.commands.pop().undo()", "purpose": "Command pattern with undo history", "explanation": "Each user action is a Command object with execute / undo. The History stack records executed commands; undo pops and reverses. Decouples invokers from receivers, enables undo/redo, transactional state changes, macro recording. Used in editors, IDE refactoring, GUI apps. For web apps, the equivalent is event-sourcing with reversible events.", "key_concepts": ["command pattern", "undo stack", "encapsulating actions"]},
    {"id": "CE-128", "language": "python", "snippet": "class Logger(ABC):\n    def log(self, level, msg):\n        if self.can_handle(level):\n            self.write(level, msg)\n        elif self.next:\n            self.next.log(level, msg)\n    @abstractmethod\n    def can_handle(self, level): ...\n    @abstractmethod\n    def write(self, level, msg): ...\n\nclass DebugLogger(Logger):\n    def __init__(self, next=None): self.next = next\n    def can_handle(self, level): return level == 'DEBUG'\n    def write(self, level, msg): print('[D]', msg)", "purpose": "Chain of Responsibility: each handler tries, passes on if not its concern", "explanation": "Each handler decides whether to handle the request or delegate to the next in line. Used in logging hierarchies, middleware chains (Express, Django, Rack), exception handling chains, security policy decisions. The chain is configured at construction time; runtime dispatch is implicit.", "key_concepts": ["chain of responsibility", "delegation", "middleware pattern"]},
    {"id": "CE-129", "language": "python", "snippet": "class Algorithm(ABC):\n    def run(self):\n        self.setup()\n        result = self.process()\n        self.teardown()\n        return result\n    def setup(self): pass\n    @abstractmethod\n    def process(self): ...\n    def teardown(self): pass\n\nclass MyAlgo(Algorithm):\n    def process(self):\n        return sum(range(100))", "purpose": "Template method: skeleton algorithm with hookable steps", "explanation": "Base class defines the algorithm shape; subclasses fill in specific steps. setup / teardown have default no-op implementations; process is mandatory. Python ABCs enforce that. Used in test frameworks (setUp / tearDown), web request lifecycle, pluggable parsers. Inversion-of-control: parent calls child methods, not the other way around.", "key_concepts": ["template method", "Hollywood principle", "skeleton + hooks"]},
    {"id": "CE-130", "language": "python", "snippet": "import asyncio\nimport websockets\n\nasync def echo(ws):\n    async for msg in ws:\n        await ws.send(f'echo: {msg}')\n\nasync def main():\n    async with websockets.serve(echo, 'localhost', 8765):\n        await asyncio.Future()  # run forever\n\nasyncio.run(main())", "purpose": "WebSocket echo server with the websockets library", "explanation": "websockets.serve binds a coroutine handler to each connection. async for msg in ws iterates incoming messages. Bidirectional: send and receive on the same socket. asyncio.Future() with no callbacks blocks forever. Production servers add ping/pong keepalive, authentication, message size limits, and reverse-proxy considerations.", "key_concepts": ["WebSockets", "async iteration on connection", "long-running asyncio main"]},
    {"id": "CE-131", "language": "python", "snippet": "from flask import Flask, Response\nimport time\napp = Flask(__name__)\n\n@app.get('/events')\ndef events():\n    def stream():\n        for i in range(10):\n            yield f'data: tick {i}\\n\\n'\n            time.sleep(1)\n    return Response(stream(), mimetype='text/event-stream')", "purpose": "Server-Sent Events endpoint streaming text events", "explanation": "SSE is HTTP server -> client streaming with reconnection semantics built in. Each event is `data: <text>\\n\\n` (double newline ends an event). MIME type text/event-stream tells the browser to treat it as SSE. Browser EventSource API connects automatically. Lighter than WebSockets when you only need one-way push (notifications, progress updates).", "key_concepts": ["Server-Sent Events", "streaming response", "double-newline framing"]},
    {"id": "CE-132", "language": "python", "snippet": "import strawberry\n\n@strawberry.type\nclass User:\n    id: int\n    name: str\n\n@strawberry.type\nclass Query:\n    @strawberry.field\n    def user(self, id: int) -> User:\n        return User(id=id, name=f'User {id}')\n\nschema = strawberry.Schema(query=Query)", "purpose": "GraphQL schema with the strawberry library", "explanation": "Decorator-driven: @strawberry.type defines a type, @strawberry.field is a resolver. The Query class is the root for queries (mutations have a separate root). The schema introspects the types to build the GraphQL SDL. Used with FastAPI, Django, Sanic. The graphene library is the older alternative; ariadne uses the schema-first approach instead of code-first.", "key_concepts": ["GraphQL", "strawberry decorators", "schema-first vs code-first"]},
    {"id": "CE-133", "language": "python", "snippet": "import pandas as pd\n\ndf = pd.read_csv('sales.csv')\ndf['total'] = df['qty'] * df['price']\nresult = (df\n    .query('total > 100')\n    .groupby('region')['total']\n    .sum()\n    .sort_values(ascending=False))", "purpose": "pandas DataFrame: read, compute, filter, group, aggregate, sort", "explanation": "Method chaining is the pandas idiom: each step returns a new (lazy-ish) frame. .query is SQL-like filter. .groupby + .sum aggregates within groups. .sort_values orders. Vectorised: the loop runs in C. For larger-than-memory data use pandas with chunksize=, polars (Rust-backed, ~10x faster), or duckdb (SQL on local files).", "key_concepts": ["pandas method chaining", "vectorised operations", "groupby aggregation"]},
    {"id": "CE-134", "language": "python", "snippet": "import polars as pl\n\nresult = (pl.read_csv('sales.csv')\n    .with_columns((pl.col('qty') * pl.col('price')).alias('total'))\n    .filter(pl.col('total') > 100)\n    .group_by('region')\n    .agg(pl.col('total').sum())\n    .sort('total', descending=True))", "purpose": "Same query in polars: faster, lazy-evaluable", "explanation": "polars is Rust-backed pandas alternative with a lazy execution mode. pl.col() builds an expression; chained operations compose into a query plan that polars optimises before executing. Multi-threaded by default. For batch ETL polars is often 5-10x faster than pandas; for one-off interactive analysis pandas is more convenient.", "key_concepts": ["polars expressions", "lazy execution", "Rust-backed performance"]},
    {"id": "CE-135", "language": "python", "snippet": "import numpy as np\n\nA = np.random.randn(1000, 1000)\nB = np.random.randn(1000, 1000)\nC = A @ B  # matrix multiply\nC.shape       # (1000, 1000)\nnp.allclose(C, A.dot(B))  # True", "purpose": "NumPy matrix multiplication via @ operator", "explanation": "@ is the matmul operator since Python 3.5; np.matmul / .dot are equivalent. Backed by LAPACK/BLAS — typically OpenBLAS or MKL — multi-threaded matrix kernels. For 1000x1000 multiplies in ~10ms on a laptop. Allclose handles floating-point comparison: array_equal would fail because of fp rounding.", "key_concepts": ["numpy", "BLAS-backed matmul", "@ operator"]},
    {"id": "CE-136", "language": "python", "snippet": "import numpy as np\nfrom scipy import stats\n\nx = np.random.randn(1000)\nresult = stats.ttest_1samp(x, 0.0)\nprint(f'p={result.pvalue:.4f} t={result.statistic:.3f}')", "purpose": "scipy one-sample t-test against population mean 0", "explanation": "ttest_1samp tests whether the sample mean differs significantly from a hypothesised population mean. Returns t-statistic and p-value. Two-tailed by default. For random standard-normal samples the p-value should be uniformly distributed on [0,1]; under-the-null tests this empirically. scipy.stats has every standard test (chi-square, ANOVA, KS, Mann-Whitney, etc.).", "key_concepts": ["t-test", "p-value", "scipy.stats"]},
    {"id": "CE-137", "language": "sql", "snippet": "WITH RECURSIVE org_chart AS (\n    SELECT id, name, manager_id, 0 AS level\n    FROM employees WHERE manager_id IS NULL\n    UNION ALL\n    SELECT e.id, e.name, e.manager_id, oc.level + 1\n    FROM employees e\n    JOIN org_chart oc ON e.manager_id = oc.id\n)\nSELECT * FROM org_chart ORDER BY level;", "purpose": "Recursive CTE traversing an org chart", "explanation": "CTE = Common Table Expression. RECURSIVE references itself: the base case picks employees with no manager (CEOs); the recursive step adds direct reports of already-found employees. Iterates until no new rows. Used for trees, hierarchies, transitive closures, paths. PostgreSQL, SQLite, SQL Server, Oracle support this; MySQL since 8.0.", "key_concepts": ["recursive CTE", "tree traversal in SQL", "transitive closure"]},
    {"id": "CE-138", "language": "sql", "snippet": "SELECT\n    user_id,\n    transaction_date,\n    amount,\n    SUM(amount) OVER (\n        PARTITION BY user_id\n        ORDER BY transaction_date\n    ) AS running_total\nFROM transactions;", "purpose": "Window function for per-user running total", "explanation": "OVER (PARTITION BY ... ORDER BY ...) defines a window: per user, ordered by date. SUM(amount) OVER (...) computes the sum from the start of the window to the current row. Other aggregates (COUNT, AVG, FIRST_VALUE, LAG, LEAD, RANK) work the same way. Cleaner than self-joins for cumulative / ranking queries.", "key_concepts": ["window function", "PARTITION BY", "running aggregate"]},
    {"id": "CE-139", "language": "javascript", "snippet": "const target = { name: 'Alice', age: 30 };\nconst handler = {\n  get(obj, prop) {\n    console.log(`reading ${prop}`);\n    return prop in obj ? obj[prop] : 'unknown';\n  },\n  set(obj, prop, value) {\n    console.log(`setting ${prop} = ${value}`);\n    obj[prop] = value;\n    return true;\n  }\n};\nconst proxy = new Proxy(target, handler);", "purpose": "JavaScript Proxy: intercept property reads and writes", "explanation": "Proxy traps every operation on its target. get / set / has / deleteProperty / etc. Used for: reactive frameworks (Vue 3 reactivity), validation (reject invalid sets), logging access, memoization, immutability checks (return false from set). Performance overhead is real, so use sparingly on hot paths.", "key_concepts": ["Proxy", "trap handlers", "metaprogramming"]},
    {"id": "CE-140", "language": "javascript", "snippet": "class BoundedInt {\n  #value;\n  constructor(initial, min, max) {\n    this.min = min; this.max = max;\n    this.value = initial;\n  }\n  get value() { return this.#value; }\n  set value(v) {\n    if (v < this.min || v > this.max) throw new RangeError('out of range');\n    this.#value = v;\n  }\n}", "purpose": "Class with getter/setter and a private field for bounded value", "explanation": "Private field #value (ES2022) is enforced by the language, not just convention. Setter validates on every write — including the constructor's `this.value = initial`. Cleaner than separate getValue/setValue methods. Combine with TypeScript readonly + branded types for compile-time guarantees.", "key_concepts": ["getter/setter", "private fields", "validation in setter"]},
    {"id": "CE-141", "language": "rust", "snippet": "use tokio::time::{sleep, Duration};\n\n#[tokio::main]\nasync fn main() {\n    let h1 = tokio::spawn(async {\n        sleep(Duration::from_secs(1)).await;\n        \"a\"\n    });\n    let h2 = tokio::spawn(async {\n        sleep(Duration::from_secs(2)).await;\n        \"b\"\n    });\n    let (a, b) = tokio::join!(h1, h2);\n    println!(\"{:?} {:?}\", a, b);\n}", "purpose": "Rust async runtime with tokio: spawn + join two tasks", "explanation": "tokio::main attribute starts the runtime around main. tokio::spawn creates a JoinHandle that runs concurrently. tokio::join! awaits both and collects their outputs. Total wall time is ~2 seconds (the slower task), not 3. async/await in Rust is opt-in: you choose the runtime (tokio, async-std, smol).", "key_concepts": ["tokio runtime", "async tasks", "join macro"]},
    {"id": "CE-142", "language": "rust", "snippet": "use std::ops::Add;\n\nfn sum<T: Add<Output = T> + Copy + Default>(items: &[T]) -> T {\n    let mut total = T::default();\n    for &x in items {\n        total = total + x;\n    }\n    total\n}", "purpose": "Generic sum function with multiple trait bounds", "explanation": "T must satisfy Add (with the same Output type), Copy (so we can use the value after iter), and Default (for the initial accumulator zero). Trait bounds appear after the colon, joined by +. The compiler monomorphises sum::<i32> and sum::<f64> into separate functions — zero runtime overhead. For richer constraints use a trait alias or a `where` clause.", "key_concepts": ["trait bounds", "generic constraints", "monomorphisation"]},
    {"id": "CE-143", "language": "go", "snippet": "type Animal interface {\n    Sound() string\n}\n\ntype Dog struct{ Name string }\nfunc (d Dog) Sound() string { return \"woof\" }\n\nfunc main() {\n    var a Animal = Dog{Name: \"Rex\"}\n    fmt.Println(a.Sound())\n}", "purpose": "Go interface: structural satisfaction via method set", "explanation": "Dog implements Animal because it has a Sound() string method — no `implements` keyword needed. The interface variable holds (concrete type, value) at runtime. Empty interface `interface{}` (or `any` since Go 1.18) accepts anything. Type assertion `a.(Dog)` extracts the concrete value or panics; the comma-ok form returns a bool.", "key_concepts": ["structural interface", "implicit satisfaction", "type assertion"]},
    {"id": "CE-144", "language": "go", "snippet": "type Animal struct {\n    Name string\n    Age  int\n}\n\ntype Dog struct {\n    Animal\n    Breed string\n}\n\nfunc main() {\n    d := Dog{Animal: Animal{Name: \"Rex\", Age: 3}, Breed: \"Lab\"}\n    fmt.Println(d.Name)  // promoted from Animal\n}", "purpose": "Struct embedding: composition with field/method promotion", "explanation": "Embedding (no field name) promotes the embedded struct's fields and methods to the outer struct. d.Name works directly without d.Animal.Name. Enables composition-over-inheritance idiom. Method sets compose: Dog gets all of Animal's methods plus its own. Conflicts are reported as compile errors if you don't explicitly disambiguate.", "key_concepts": ["struct embedding", "field promotion", "composition over inheritance"]},
    {"id": "CE-145", "language": "python", "snippet": "import msgpack\n\ndata = {'user_id': 42, 'tags': ['a', 'b'], 'value': 3.14}\nblob = msgpack.packb(data)\nprint(len(blob), 'bytes')  # ~30 bytes\nrecovered = msgpack.unpackb(blob)", "purpose": "MessagePack: binary serialisation, more compact than JSON", "explanation": "MessagePack encodes the same data structure as JSON but in binary form. Typically 30-50% smaller, faster to encode/decode. Schema-less like JSON. Used in: Redis pub/sub, real-time game protocols, log shipping, IPC between languages. For schema-validated binary, protobuf or capnproto are the choices.", "key_concepts": ["msgpack", "binary serialisation", "JSON alternative"]},
    {"id": "CE-146", "language": "python", "snippet": "from google.protobuf import descriptor_pb2\nimport user_pb2  # generated from user.proto\n\nuser = user_pb2.User(id=1, name='Alice', email='a@b.c')\nblob = user.SerializeToString()\nrecovered = user_pb2.User()\nrecovered.ParseFromString(blob)", "purpose": "Protobuf serialisation for typed cross-language messages", "explanation": "Schema defined in .proto file; protoc generates language-specific bindings. Serialisation is binary, schema-validated, very compact (variable-length integers, tag-encoded fields). Forward and backward compatibility via reserved tag numbers. Used in gRPC, Kafka, Google internal systems. Cap'n Proto and FlatBuffers are zero-copy alternatives.", "key_concepts": ["protobuf", "code generation", "wire-format compatibility"]},
    {"id": "CE-147", "language": "yaml", "snippet": "apiVersion: v1\nkind: Pod\nmetadata:\n  name: web\nspec:\n  containers:\n  - name: web\n    image: nginx:1.27\n    livenessProbe:\n      httpGet:\n        path: /healthz\n        port: 80\n      initialDelaySeconds: 5\n      periodSeconds: 10\n    readinessProbe:\n      httpGet:\n        path: /ready\n        port: 80", "purpose": "Kubernetes Pod manifest with liveness + readiness probes", "explanation": "livenessProbe: kubelet kills the container if this fails — recovery from deadlock. readinessProbe: removes the pod from Service endpoints when failing — drains traffic for slow startup or transient issues. periodSeconds: how often to probe. initialDelaySeconds: grace period after start. Always set both for production HTTP services.", "key_concepts": ["Kubernetes probes", "liveness vs readiness", "Pod spec"]},
    {"id": "CE-148", "language": "python", "snippet": "from typing import cast\n\ndef get_value(obj: object) -> str:\n    # We KNOW obj is a str at this point even if mypy doesn't.\n    return cast(str, obj).upper()", "purpose": "typing.cast: tell the type checker what type something is at runtime", "explanation": "cast(T, x) returns x unchanged at runtime — no type check happens. It's purely an annotation telling mypy/pyright that the value is T. Use sparingly: each cast is a place where you're overriding the type checker. Better to use isinstance + narrowing where possible. typing.assert_type checks at type-check time without changing runtime.", "key_concepts": ["typing.cast", "type narrowing", "no-op at runtime"]},
    {"id": "CE-149", "language": "python", "snippet": "from typing import assert_never\n\ndef handle(status: 'Status') -> str:\n    if status == 'pending': return 'wait'\n    if status == 'done': return 'ok'\n    if status == 'failed': return 'retry'\n    assert_never(status)", "purpose": "Exhaustiveness check with typing.assert_never", "explanation": "assert_never (PEP 676, 3.11+) tells mypy that this code path is unreachable — typically used at the bottom of an if/elif chain over a Literal-typed value. If you add a new variant to Status without adding a branch, mypy errors at the assert_never call. Replicates the exhaustive-match safety Rust gives you for free.", "key_concepts": ["assert_never", "exhaustive checking", "Literal types"]},
    {"id": "CE-150", "language": "python", "snippet": "from functools import cached_property\nimport time\n\nclass DataLoader:\n    @cached_property\n    def data(self):\n        # expensive computation runs once per instance\n        time.sleep(2)\n        return list(range(1000))\n\nl = DataLoader()\nl.data  # 2 seconds\nl.data  # instant — cached on the instance dict", "purpose": "@cached_property memoizes per-instance, replacing itself in the dict", "explanation": "Unlike @property which recomputes on every access, @cached_property writes into the instance __dict__ on first access; subsequent reads bypass the descriptor and return the cached value directly. Cache is per-instance, not shared. To invalidate: del instance.data. functools.lru_cache with method cache key works for class methods but caches across instances unless you parameterise on self.", "key_concepts": ["cached_property", "lazy attribute", "per-instance caching"]},
    {"id": "CE-151", "language": "shell", "snippet": "#!/bin/bash\nset -euo pipefail\n\n# Find all Python files modified in the last 7 days, count lines.\nfind . -name '*.py' -type f -mtime -7 \\\n  | xargs wc -l \\\n  | sort -n", "purpose": "Composing find / xargs / wc / sort to count recent Python lines", "explanation": "find emits paths, xargs converts them into wc arguments. wc -l counts lines per file plus a total. sort -n orders numerically. The pipeline is the canonical Unix way to combine specialised tools. Caveat: filenames with spaces break this; use find -print0 + xargs -0 for safety.", "key_concepts": ["find / xargs / sort pipeline", "Unix tool composition"]},
    {"id": "CE-152", "language": "shell", "snippet": "#!/bin/bash\nset -euo pipefail\n\n# Run a command on every file in parallel, 8 at a time.\nfind logs -name '*.log' -print0 \\\n  | xargs -0 -n 1 -P 8 gzip", "purpose": "xargs -P for parallel command execution", "explanation": "xargs -P 8 runs up to 8 commands in parallel. -n 1 means one argument per command invocation. -print0 + -0 handle filenames with spaces / newlines correctly. GNU parallel is the more featureful alternative (rate limit, retries, halt-on-error). For most ad-hoc cases xargs -P does the job.", "key_concepts": ["parallel execution", "xargs -P", "null-separated paths"]},
    {"id": "CE-153", "language": "python", "snippet": "from collections import OrderedDict\n\ndef ordered_set(items):\n    return list(OrderedDict.fromkeys(items))\n\nresult = ordered_set([1, 2, 3, 2, 1, 4])\n# [1, 2, 3, 4]", "purpose": "Order-preserving deduplication", "explanation": "Plain set() drops duplicates but loses order. OrderedDict.fromkeys preserves insertion order while making keys unique. Python 3.7+ regular dict also preserves order, so dict.fromkeys works too. For very large inputs both are O(n) memory. dataclasses_json or the ordered-set package give a proper Set type with order.", "key_concepts": ["order-preserving dedup", "dict.fromkeys trick", "OrderedDict still useful for explicit-order intent"]},
    {"id": "CE-154", "language": "python", "snippet": "import dataclasses\n\n@dataclasses.dataclass\nclass Point:\n    x: float\n    y: float\n\np1 = Point(1.0, 2.0)\np2 = dataclasses.replace(p1, y=5.0)\n# p2 is a NEW Point(1.0, 5.0); p1 unchanged", "purpose": "Functional update of a dataclass via dataclasses.replace", "explanation": "replace returns a new instance with the named fields overridden. Original is untouched. Useful for immutable-style updates without writing a manual copy constructor. Works with frozen=True dataclasses for full immutability. namedtuple has _replace for the same pattern.", "key_concepts": ["dataclasses.replace", "functional update", "immutability friendly"]},
    {"id": "CE-155", "language": "python", "snippet": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t(x INT)')\nwith conn:  # transaction\n    conn.execute('INSERT INTO t VALUES (1)')\n    conn.execute('INSERT INTO t VALUES (2)')\n# transaction commits at exit; rolls back on exception", "purpose": "SQLite connection as a transaction context manager", "explanation": "sqlite3.Connection's __enter__/__exit__ start a transaction on entry, commit on success, roll back on exception. Cleaner than explicit conn.commit() / conn.rollback(). Note: this only works for the connection itself; for cursors use them within the connection's `with` block. PostgreSQL psycopg has the same pattern.", "key_concepts": ["transaction context manager", "automatic commit/rollback", "DB-API"]},
    {"id": "CE-156", "language": "python", "snippet": "from concurrent.futures import ProcessPoolExecutor\n\ndef cpu_heavy(n):\n    return sum(i * i for i in range(n))\n\nwith ProcessPoolExecutor() as ex:\n    results = list(ex.map(cpu_heavy, [10**6] * 8))", "purpose": "ProcessPoolExecutor parallelism for CPU-bound work", "explanation": "Spawns separate Python processes (sidesteps the GIL). Default workers = os.cpu_count(). map distributes inputs to workers and gathers results in input order. submit + as_completed gives more control. Use Process for CPU-bound work; Thread for I/O-bound. Pickling overhead means the input/output should be coarse-grained (one task = significant work).", "key_concepts": ["ProcessPoolExecutor", "GIL bypass", "CPU-bound parallelism"]},
    {"id": "CE-157", "language": "python", "snippet": "import os\nimport tempfile\n\nwith tempfile.TemporaryDirectory() as tmp:\n    path = os.path.join(tmp, 'work.txt')\n    with open(path, 'w') as f:\n        f.write('scratch data')\n    # tmp is automatically deleted at __exit__", "purpose": "Self-cleaning temporary directory via context manager", "explanation": "TemporaryDirectory creates a fresh tmp directory in the system tmp area, returns its path. On context exit it recursively deletes the dir + everything in it. Useful for tests that need a writable scratch area without manual cleanup. NamedTemporaryFile and SpooledTemporaryFile are the file-level variants.", "key_concepts": ["TemporaryDirectory", "automatic cleanup", "test scratch area"]},
    {"id": "CE-158", "language": "python", "snippet": "import re\n\ndef camel_to_snake(s: str) -> str:\n    return re.sub(r'(?<!^)(?=[A-Z])', '_', s).lower()\n\ncamel_to_snake('myCamelCaseVar')\n# 'my_camel_case_var'", "purpose": "Camel-to-snake-case via regex lookahead", "explanation": "(?<!^) is a negative lookbehind that disallows match-at-start (so 'MyVar' doesn't get a leading underscore). (?=[A-Z]) is a positive lookahead matching position before any capital letter. The match is zero-width — substituting '_' inserts at that position. Then lowercase the whole string.", "key_concepts": ["lookahead / lookbehind", "zero-width match", "case conversion"]},
    {"id": "CE-159", "language": "python", "snippet": "import functools\n\n@functools.lru_cache(maxsize=128)\ndef fib(n: int) -> int:\n    if n < 2: return n\n    return fib(n-1) + fib(n-2)\n\nfib.cache_info()  # CacheInfo(hits=N, misses=M, maxsize=128, currsize=...)", "purpose": "lru_cache with cache_info inspection", "explanation": "lru_cache memoizes by argument tuple. maxsize limits memory; lru evicts least-recently-used. cache_info shows hits/misses for performance debugging. cache_clear empties the cache. typed=True caches int(1) and float(1.0) separately. For Python 3.9+, functools.cache is unbounded lru_cache (maxsize=None).", "key_concepts": ["lru_cache", "cache_info", "memoization with eviction"]},
    {"id": "CE-160", "language": "python", "snippet": "import json\nfrom typing import Any\n\nclass StrictDict(dict):\n    def __setitem__(self, k: Any, v: Any) -> None:\n        if k in self:\n            raise KeyError(f'duplicate key: {k!r}')\n        super().__setitem__(k, v)\n\nd = json.loads('{\"a\": 1, \"a\": 2}', object_pairs_hook=StrictDict)\n# raises KeyError on duplicate\n", "purpose": "Detect duplicate keys when parsing JSON", "explanation": "Standard json.loads silently keeps the last value when a key appears twice — the second `a` overwrites the first. object_pairs_hook lets you intercept the (k, v) list before the dict is built. StrictDict raises on the second insert. Useful for config validation, schema-strict parsing, security-sensitive deserialization.", "key_concepts": ["object_pairs_hook", "duplicate-key detection", "strict parsing"]},
]


WRITE_PATTERNS = [
    {"id": "CW-121", "language": "python", "description": "Implement a trie data structure with insert and search", "implementation": "class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.end = False\n\nclass Trie:\n    def __init__(self):\n        self.root = TrieNode()\n    def insert(self, word):\n        node = self.root\n        for ch in word:\n            node = node.children.setdefault(ch, TrieNode())\n        node.end = True\n    def search(self, word):\n        node = self.root\n        for ch in word:\n            if ch not in node.children: return False\n            node = node.children[ch]\n        return node.end", "explanation": "Each node has a dict of children and a flag marking complete words. insert and search are both O(L) where L is the word length. setdefault handles the missing-child case. For prefix search add a separate starts_with method that returns True even if .end is False at the matched node."},
    {"id": "CW-122", "language": "python", "description": "Implement Floyd-Warshall all-pairs shortest paths", "implementation": "def floyd_warshall(graph: list[list[int]]) -> list[list[int]]:\n    n = len(graph)\n    dist = [row[:] for row in graph]\n    for k in range(n):\n        for i in range(n):\n            for j in range(n):\n                if dist[i][k] + dist[k][j] < dist[i][j]:\n                    dist[i][j] = dist[i][k] + dist[k][j]\n    return dist", "explanation": "Triple-nested loop, O(V^3). dist[i][j] is the shortest path using only nodes 0..k as intermediates after the k-th outer iteration. Initialise non-edges with float('inf'); diagonal with 0. Detects negative cycles when dist[i][i] < 0 after the loop completes."},
    {"id": "CW-123", "language": "python", "description": "Implement A* search with a heuristic", "implementation": "from heapq import heappush, heappop\ndef a_star(start, goal, neighbours, h):\n    open_set = [(h(start), 0, start)]\n    came_from, g = {}, {start: 0}\n    while open_set:\n        _, gx, x = heappop(open_set)\n        if x == goal:\n            path = [x]\n            while path[-1] in came_from:\n                path.append(came_from[path[-1]])\n            return list(reversed(path))\n        for n, cost in neighbours(x):\n            new_g = gx + cost\n            if new_g < g.get(n, float('inf')):\n                g[n], came_from[n] = new_g, x\n                heappush(open_set, (new_g + h(n), new_g, n))\n    return None", "explanation": "Heap ordered by f = g + h. neighbours(x) returns (node, edge_cost) pairs. h(x) estimates distance from x to goal. If h is admissible (never overestimates), A* finds optimal paths. Reconstructs path via came_from parent pointers."},
    {"id": "CW-124", "language": "python", "description": "Implement Tarjan's SCC algorithm", "implementation": "def tarjan_scc(graph):\n    index, lowlink, on_stack = {}, {}, set()\n    stack, sccs = [], []\n    counter = [0]\n    def visit(u):\n        index[u] = lowlink[u] = counter[0]\n        counter[0] += 1\n        stack.append(u); on_stack.add(u)\n        for v in graph.get(u, []):\n            if v not in index:\n                visit(v)\n                lowlink[u] = min(lowlink[u], lowlink[v])\n            elif v in on_stack:\n                lowlink[u] = min(lowlink[u], index[v])\n        if lowlink[u] == index[u]:\n            comp = []\n            while True:\n                w = stack.pop(); on_stack.discard(w)\n                comp.append(w)\n                if w == u: break\n            sccs.append(comp)\n    for u in graph:\n        if u not in index: visit(u)\n    return sccs", "explanation": "Single DFS pass. SCCs emerge when a node's lowlink equals its index (root of an SCC). Used for cycle detection, 2-SAT, condensation of digraphs into DAGs. O(V + E)."},
    {"id": "CW-125", "language": "python", "description": "Implement a segment tree with point update + range sum query", "implementation": "class SegTree:\n    def __init__(self, arr):\n        self.n = len(arr)\n        self.tree = [0] * (4 * self.n)\n        self._build(arr, 1, 0, self.n - 1)\n    def _build(self, a, v, l, r):\n        if l == r: self.tree[v] = a[l]; return\n        m = (l + r) // 2\n        self._build(a, 2*v, l, m); self._build(a, 2*v+1, m+1, r)\n        self.tree[v] = self.tree[2*v] + self.tree[2*v+1]\n    def update(self, i, val): self._update(1, 0, self.n-1, i, val)\n    def _update(self, v, l, r, i, val):\n        if l == r: self.tree[v] = val; return\n        m = (l + r) // 2\n        if i <= m: self._update(2*v, l, m, i, val)\n        else: self._update(2*v+1, m+1, r, i, val)\n        self.tree[v] = self.tree[2*v] + self.tree[2*v+1]\n    def query(self, ql, qr): return self._query(1, 0, self.n-1, ql, qr)\n    def _query(self, v, l, r, ql, qr):\n        if qr < l or r < ql: return 0\n        if ql <= l and r <= qr: return self.tree[v]\n        m = (l + r) // 2\n        return self._query(2*v, l, m, ql, qr) + self._query(2*v+1, m+1, r, ql, qr)", "explanation": "Tree stored as an array (left child = 2v, right = 2v+1). O(n) build, O(log n) update + query. For min/max queries replace + with min/max. For range updates with lazy propagation, add a lazy[] array and push down before recurse."},
    {"id": "CW-126", "language": "python", "description": "Implement the visitor pattern for a simple AST", "implementation": "from abc import ABC, abstractmethod\nclass Node(ABC):\n    @abstractmethod\n    def accept(self, v): ...\n\nclass Num(Node):\n    def __init__(self, val): self.val = val\n    def accept(self, v): return v.visit_num(self)\n\nclass Add(Node):\n    def __init__(self, l, r): self.l, self.r = l, r\n    def accept(self, v): return v.visit_add(self)\n\nclass Eval:\n    def visit_num(self, n): return n.val\n    def visit_add(self, n): return n.l.accept(self) + n.r.accept(self)\n\ntree = Add(Num(1), Add(Num(2), Num(3)))\nprint(tree.accept(Eval()))  # 6", "explanation": "Each node calls back to a visitor's type-specific method. Adding new operations (Print, TypeCheck) is a new visitor class. Adding new node types requires touching every visitor — that's the visitor pattern's structural tradeoff."},
    {"id": "CW-127", "language": "python", "description": "Implement the command pattern with undo support", "implementation": "from abc import ABC, abstractmethod\nclass Command(ABC):\n    @abstractmethod\n    def execute(self): ...\n    @abstractmethod\n    def undo(self): ...\n\nclass AddItem(Command):\n    def __init__(self, lst, item):\n        self.lst, self.item = lst, item\n    def execute(self): self.lst.append(self.item)\n    def undo(self):\n        if self.lst and self.lst[-1] == self.item:\n            self.lst.pop()\n\nclass History:\n    def __init__(self): self.stack = []\n    def do(self, cmd):\n        cmd.execute(); self.stack.append(cmd)\n    def undo(self):\n        if self.stack: self.stack.pop().undo()", "explanation": "Each user action is a Command with execute + undo methods. History records the stack for undo / redo. Used in editors, GUI apps, replay debuggers. For redo: track a redo stack alongside; clear it on every new do()."},
    {"id": "CW-128", "language": "python", "description": "Implement a chain of responsibility for log handling", "implementation": "class LogHandler:\n    def __init__(self, level, next_=None):\n        self.level, self.next_ = level, next_\n    def log(self, level, msg):\n        if level == self.level:\n            print(f'[{level}] {msg}')\n        elif self.next_:\n            self.next_.log(level, msg)\n\nchain = LogHandler('DEBUG', LogHandler('INFO', LogHandler('ERROR')))\nchain.log('INFO', 'hello')", "explanation": "Each handler decides whether to handle the request or delegate to the next. Used in middleware, security policy chains, exception handling. The chain is built at construction time; runtime dispatch follows the linked list. Adding a handler is one constructor call."},
    {"id": "CW-129", "language": "python", "description": "Build a WebSocket echo server with the websockets library", "implementation": "import asyncio\nimport websockets\n\nasync def echo(ws):\n    async for msg in ws:\n        await ws.send(f'echo: {msg}')\n\nasync def main():\n    async with websockets.serve(echo, 'localhost', 8765):\n        await asyncio.Future()  # run forever\n\nasyncio.run(main())", "explanation": "websockets.serve binds the handler to each connection. async for iterates incoming frames; await ws.send pushes back. asyncio.Future() with no callbacks blocks main forever. Production servers add ping/pong, auth, max message size, behind a reverse proxy."},
    {"id": "CW-130", "language": "python", "description": "Build a Server-Sent Events endpoint with Flask", "implementation": "from flask import Flask, Response\nimport time\napp = Flask(__name__)\n\n@app.get('/events')\ndef events():\n    def stream():\n        for i in range(10):\n            yield f'data: event {i}\\n\\n'\n            time.sleep(1)\n    return Response(stream(), mimetype='text/event-stream')", "explanation": "SSE: HTTP server-to-client streaming. Each event is `data: <text>\\n\\n` (double newline ends an event). Browsers reconnect automatically on disconnect via the EventSource API. Lighter than WebSockets for one-way push. For Django, StreamingHttpResponse plays the same role."},
    {"id": "CW-131", "language": "python", "description": "Build a simple GraphQL schema with Strawberry", "implementation": "import strawberry\n\n@strawberry.type\nclass User:\n    id: int\n    name: str\n\n@strawberry.type\nclass Query:\n    @strawberry.field\n    def user(self, id: int) -> User:\n        return User(id=id, name=f'User {id}')\n\nschema = strawberry.Schema(query=Query)", "explanation": "Strawberry uses Python type annotations to drive schema generation. @strawberry.type makes a GraphQL type, @strawberry.field is a resolver. Mutations use a separate root class. For ASGI servers (FastAPI, Starlette), Strawberry has integrations. Graphene is the older alternative."},
    {"id": "CW-132", "language": "python", "description": "Read a CSV with pandas and compute group totals", "implementation": "import pandas as pd\ndef totals_by_region(path: str) -> pd.Series:\n    df = pd.read_csv(path)\n    df['total'] = df['qty'] * df['price']\n    return (df\n        .query('total > 100')\n        .groupby('region')['total']\n        .sum()\n        .sort_values(ascending=False))", "explanation": "Method chaining is the pandas idiom. .query is SQL-like filter; .groupby + .sum aggregates per group; .sort_values orders descending. Vectorised arithmetic; no Python loop. For larger-than-memory data switch to polars or duckdb."},
    {"id": "CW-133", "language": "python", "description": "Run a parallel CPU-bound workload across processes", "implementation": "from concurrent.futures import ProcessPoolExecutor\n\ndef heavy(n):\n    return sum(i * i for i in range(n))\n\ndef parallel_sum_squares(ns: list[int]) -> list[int]:\n    with ProcessPoolExecutor() as ex:\n        return list(ex.map(heavy, ns))", "explanation": "ProcessPoolExecutor spawns separate processes (sidesteps the GIL). Default worker count = os.cpu_count(). map distributes inputs and gathers in input order. Pickling overhead means each task should be coarse-grained. For thread-pool I/O-bound work use ThreadPoolExecutor instead."},
    {"id": "CW-134", "language": "python", "description": "Compute a t-test against a hypothesised mean", "implementation": "import numpy as np\nfrom scipy import stats\n\ndef one_sample_ttest(sample, mu0=0.0):\n    arr = np.asarray(sample)\n    result = stats.ttest_1samp(arr, mu0)\n    return {'t': result.statistic, 'p': result.pvalue}", "explanation": "ttest_1samp tests whether the sample mean differs from mu0. Returns t-statistic and two-tailed p-value. For comparing two samples use ttest_ind (independent) or ttest_rel (paired). For non-parametric Mann-Whitney U use stats.mannwhitneyu."},
    {"id": "CW-135", "language": "sql", "description": "Write a recursive CTE to build an org chart", "implementation": "WITH RECURSIVE org AS (\n    SELECT id, name, manager_id, 0 AS level\n    FROM employees WHERE manager_id IS NULL\n    UNION ALL\n    SELECT e.id, e.name, e.manager_id, o.level + 1\n    FROM employees e JOIN org o ON e.manager_id = o.id\n)\nSELECT * FROM org ORDER BY level;", "explanation": "Recursive CTE: base case picks roots (employees with no manager). Recursive step adds direct reports. Iterates until no new rows. Postgres / SQLite / MSSQL / Oracle support this; MySQL since 8.0. Used for trees, hierarchies, transitive closures, paths."},
    {"id": "CW-136", "language": "sql", "description": "Write a window function for cumulative running totals", "implementation": "SELECT\n    user_id,\n    transaction_date,\n    amount,\n    SUM(amount) OVER (\n        PARTITION BY user_id\n        ORDER BY transaction_date\n    ) AS running_total\nFROM transactions\nORDER BY user_id, transaction_date;", "explanation": "OVER (PARTITION BY ... ORDER BY ...) defines a window: per user, ordered by date. SUM(amount) OVER (...) is cumulative within the window. ROW_NUMBER, RANK, DENSE_RANK, LEAD, LAG, FIRST_VALUE, NTILE all use the same OVER clause."},
    {"id": "CW-137", "language": "javascript", "description": "Wrap an object in a Proxy that logs all reads", "implementation": "function logged(obj) {\n  return new Proxy(obj, {\n    get(target, prop) {\n      console.log(`reading ${String(prop)}`);\n      return target[prop];\n    }\n  });\n}\n\nconst p = logged({ name: 'Alice', age: 30 });\nconsole.log(p.name);  // logs 'reading name' then 'Alice'", "explanation": "Proxy traps every operation on its target. get / set / has / deleteProperty / etc. Used for: reactive frameworks (Vue 3), validation, logging, memoization. Performance overhead is real, so use sparingly on hot paths."},
    {"id": "CW-138", "language": "javascript", "description": "Define a class with private fields and a getter/setter", "implementation": "class Counter {\n  #value = 0;\n  get value() { return this.#value; }\n  set value(v) {\n    if (typeof v !== 'number' || v < 0) throw new TypeError('non-negative number required');\n    this.#value = v;\n  }\n  inc() { this.#value++; }\n}", "explanation": "ES2022 # prefix makes truly private fields (no name mangling, can't be accessed from outside). Getter / setter syntax exposes #value as a normal property. Setter validates on every write. Combine with TypeScript readonly for compile-time guarantees."},
    {"id": "CW-139", "language": "rust", "description": "Spawn two async tasks with tokio and join them", "implementation": "use tokio::time::{sleep, Duration};\n\n#[tokio::main]\nasync fn main() {\n    let h1 = tokio::spawn(async {\n        sleep(Duration::from_secs(1)).await;\n        \"a\"\n    });\n    let h2 = tokio::spawn(async {\n        sleep(Duration::from_secs(2)).await;\n        \"b\"\n    });\n    let (a, b) = tokio::join!(h1, h2);\n    println!(\"{:?} {:?}\", a, b);\n}", "explanation": "tokio::main attribute starts the runtime around main. spawn creates a JoinHandle that runs concurrently. join! awaits both. Total wall time = max(1, 2) = ~2 sec, not 3. async/await in Rust opt-in: pick a runtime (tokio is the standard)."},
    {"id": "CW-140", "language": "rust", "description": "Write a generic sum function with multiple trait bounds", "implementation": "use std::ops::Add;\n\nfn sum<T>(items: &[T]) -> T\nwhere\n    T: Add<Output = T> + Copy + Default,\n{\n    let mut total = T::default();\n    for &x in items {\n        total = total + x;\n    }\n    total\n}", "explanation": "T must satisfy Add (with same Output), Copy (value reused after iter), Default (zero accumulator). where-clause is more readable than inline bounds for many constraints. Compiler monomorphises sum::<i32> and sum::<f64> separately — zero runtime cost."},
    {"id": "CW-141", "language": "go", "description": "Implement an interface and verify at compile time", "implementation": "type Animal interface {\n    Sound() string\n}\n\ntype Dog struct{ Name string }\nfunc (d Dog) Sound() string { return \"woof\" }\n\n// Compile-time check that Dog satisfies Animal:\nvar _ Animal = (*Dog)(nil)", "explanation": "`var _ Animal = (*Dog)(nil)` is the canonical compile-time interface satisfaction check. If Dog ever stops satisfying Animal, the build breaks. Go interfaces are structural — no `implements` keyword. The empty `_` discards the assigned value."},
    {"id": "CW-142", "language": "go", "description": "Use struct embedding for composition", "implementation": "type Animal struct {\n    Name string\n    Age  int\n}\nfunc (a Animal) Greet() string { return \"hello, \" + a.Name }\n\ntype Dog struct {\n    Animal\n    Breed string\n}\n\n// Dog inherits Animal's Greet method via embedding.\nd := Dog{Animal: Animal{Name: \"Rex\", Age: 3}, Breed: \"Lab\"}\nd.Greet()", "explanation": "Embedding (no field name) promotes the inner struct's fields and methods to the outer. d.Greet() works directly. Composition over inheritance. For multiple embeds, conflicting names must be disambiguated (d.Animal.Name vs d.OtherEmbed.Name)."},
    {"id": "CW-143", "language": "python", "description": "Encode and decode a value with MessagePack", "implementation": "import msgpack\n\ndef encode(obj) -> bytes:\n    return msgpack.packb(obj)\n\ndef decode(blob: bytes):\n    return msgpack.unpackb(blob)\n\n# Round trip:\ndata = {'user_id': 42, 'tags': ['a', 'b'], 'value': 3.14}\nblob = encode(data)\nrecovered = decode(blob)", "explanation": "MessagePack is binary JSON: 30-50% smaller, faster encode/decode. Schema-less. Used in Redis pub/sub, real-time game protocols, IPC. For schema-validated binary use protobuf or Cap'n Proto instead."},
    {"id": "CW-144", "language": "python", "description": "Use typing.cast to suppress a type-checker complaint", "implementation": "from typing import cast\n\ndef get_str(d: dict) -> str:\n    val = d.get('key')\n    # We have invariant proof val is str even though dict.get returns Any.\n    return cast(str, val).upper()", "explanation": "cast(T, x) is a no-op at runtime — it only changes what the type checker thinks the type is. Use sparingly: each cast is a place where you're overriding the checker. Prefer isinstance + narrowing where possible. typing.assert_type checks at type-check time without runtime effect."},
    {"id": "CW-145", "language": "python", "description": "Use functools.cached_property for an expensive lazy attribute", "implementation": "from functools import cached_property\n\nclass DataLoader:\n    def __init__(self, source: str):\n        self.source = source\n    @cached_property\n    def data(self) -> list[int]:\n        # expensive computation runs once per instance\n        with open(self.source) as f:\n            return [int(x) for x in f.read().split()]", "explanation": "cached_property writes into the instance __dict__ on first access; subsequent reads bypass the descriptor (faster than @property). Per-instance, not shared. To invalidate: del instance.data. For methods (not properties), use functools.lru_cache parameterised on self carefully."},
    {"id": "CW-146", "language": "python", "description": "Detect duplicate keys when parsing JSON", "implementation": "import json\nclass StrictDict(dict):\n    def __setitem__(self, k, v):\n        if k in self:\n            raise KeyError(f'duplicate key: {k!r}')\n        super().__setitem__(k, v)\n\ndef strict_loads(s: str):\n    return json.loads(s, object_pairs_hook=StrictDict)\n\nstrict_loads('{\"a\": 1, \"a\": 2}')  # raises KeyError", "explanation": "Standard json.loads silently keeps the last value when a key appears twice. object_pairs_hook intercepts the (k, v) pairs before the dict is built. StrictDict raises on duplicate insert. Useful for schema-strict parsing, security-sensitive deserialization, configuration validation."},
    {"id": "CW-147", "language": "python", "description": "Order-preserving deduplication of a list", "implementation": "def ordered_dedup(items):\n    seen = set()\n    out = []\n    for x in items:\n        if x not in seen:\n            seen.add(x)\n            out.append(x)\n    return out\n\n# or terser, exploiting dict.fromkeys:\ndef ordered_dedup2(items):\n    return list(dict.fromkeys(items))", "explanation": "set() loses order; dict.fromkeys preserves it (Python 3.7+). The hand-rolled version with a separate `seen` set is equally fast and works on any Python. For very large inputs both are O(n) in time and memory."},
    {"id": "CW-148", "language": "python", "description": "Functional update of a dataclass via dataclasses.replace", "implementation": "import dataclasses\n\n@dataclasses.dataclass\nclass Point:\n    x: float\n    y: float\n\np1 = Point(1.0, 2.0)\np2 = dataclasses.replace(p1, y=5.0)\n# p2 = Point(1.0, 5.0); p1 unchanged", "explanation": "replace returns a new instance with the named fields overridden. Original is untouched. Useful for immutable-style updates without writing copy constructors. Works with frozen=True dataclasses for full immutability. namedtuple has _replace for the same pattern."},
    {"id": "CW-149", "language": "python", "description": "Use sqlite3.Connection as a transaction context manager", "implementation": "import sqlite3\n\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t(x INT)')\nwith conn:\n    conn.execute('INSERT INTO t VALUES (1)')\n    conn.execute('INSERT INTO t VALUES (2)')\n# transaction commits at exit; rolls back on exception", "explanation": "sqlite3.Connection's __enter__/__exit__ start a transaction on entry and commit on success / roll back on exception. Cleaner than explicit conn.commit() + conn.rollback() in try/except. Postgres psycopg has the same pattern."},
    {"id": "CW-150", "language": "python", "description": "Convert camelCase string to snake_case", "implementation": "import re\ndef camel_to_snake(s: str) -> str:\n    return re.sub(r'(?<!^)(?=[A-Z])', '_', s).lower()\n\ncamel_to_snake('myCamelVar')  # 'my_camel_var'", "explanation": "(?<!^) is a negative lookbehind so the start of string doesn't get an underscore. (?=[A-Z]) is a positive lookahead for any capital letter. The match is zero-width, so substituting '_' inserts at the position. Then lowercase the whole string."},
    {"id": "CW-151", "language": "python", "description": "Configure logging declaratively with dictConfig", "implementation": "import logging.config\n\nLOGGING = {\n    'version': 1,\n    'formatters': {\n        'std': {'format': '%(asctime)s %(levelname)s %(name)s %(message)s'},\n    },\n    'handlers': {\n        'console': {'class': 'logging.StreamHandler',\n                    'formatter': 'std', 'level': 'INFO'},\n    },\n    'loggers': {\n        'myapp': {'handlers': ['console'], 'level': 'DEBUG',\n                  'propagate': False},\n    },\n}\nlogging.config.dictConfig(LOGGING)", "explanation": "dictConfig accepts a structured dict. Cleaner than imperative basicConfig + addHandler. Production code typically loads this from YAML / JSON. structlog or python-json-logger replace the formatter for structured (JSON) logs."},
    {"id": "CW-152", "language": "python", "description": "Build an ASGI middleware that adds a request ID header", "implementation": "import uuid\nasync def request_id_middleware(scope, receive, send):\n    if scope['type'] != 'http':\n        return\n    rid = uuid.uuid4().hex\n    async def wrapped_send(message):\n        if message['type'] == 'http.response.start':\n            message.setdefault('headers', []).append(\n                (b'x-request-id', rid.encode()))\n        await send(message)\n    return wrapped_send", "explanation": "ASGI middleware wraps send to inject a header into the response start message. Each request gets a fresh UUID. For richer middleware (auth, CORS, gzip) use Starlette / FastAPI's BaseHTTPMiddleware which gives you a Request/Response abstraction."},
    {"id": "CW-153", "language": "python", "description": "Write a typed function that returns a Literal value", "implementation": "from typing import Literal\n\ndef status_code(level: str) -> Literal[200, 400, 500]:\n    if level == 'ok': return 200\n    if level == 'bad_input': return 400\n    return 500", "explanation": "Literal types let mypy reason about specific values, not just types. Caller can switch on the return Literal exhaustively (with assert_never). Useful for status codes, action enums, anything with a fixed small set of valid values. Runtime sees plain ints; checking is type-time only."},
    {"id": "CW-154", "language": "python", "description": "Build a pytest fixture with cleanup using yield", "implementation": "import pytest\nimport tempfile\n\n@pytest.fixture\ndef temp_db():\n    with tempfile.NamedTemporaryFile() as f:\n        yield f.name  # test gets the path\n    # cleanup happens automatically when the with-block exits", "explanation": "yield separates setup (before yield) from teardown (after yield). The TemporaryDirectory wraps the cleanup, so the manual `os.unlink` is redundant. scope='function' (default) gives each test its own; scope='module' / 'session' shares across multiple tests."},
    {"id": "CW-155", "language": "python", "description": "Stream a generator output to stdout as JSONL", "implementation": "import json, sys\ndef stream_jsonl(records):\n    for r in records:\n        sys.stdout.write(json.dumps(r, ensure_ascii=False) + '\\n')\n        sys.stdout.flush()", "explanation": "JSONL = one JSON object per line. flush after each line so consumers (tee | jq | tail -f) see records in real time, not in OS-page-buffered chunks. Useful for pipeline-friendly CLI tools, log producers, ML data pipelines."},
    {"id": "CW-156", "language": "python", "description": "Iterate dict in sorted key order without copying", "implementation": "d = {'b': 2, 'a': 1, 'c': 3}\nfor k in sorted(d):\n    print(k, d[k])", "explanation": "sorted(d) returns a sorted list of keys (calls iter(d) under the hood, equivalent to sorted(d.keys())). For very large dicts this allocates a list of N keys; alternatives are SortedDict (sortedcontainers) or BTreeMap-like libraries. For sorting by value: sorted(d.items(), key=lambda kv: kv[1])."},
    {"id": "CW-157", "language": "python", "description": "Find the longest common prefix of a list of strings", "implementation": "def longest_common_prefix(strs: list[str]) -> str:\n    if not strs: return ''\n    s_min, s_max = min(strs), max(strs)\n    for i, c in enumerate(s_min):\n        if c != s_max[i]:\n            return s_min[:i]\n    return s_min", "explanation": "min and max use lexicographic order: only the lex-smallest and lex-largest strings can differ from the common prefix. Walk both until they diverge. O(n + m) where n is total chars and m is min string length. Beats O(n*m) naive prefix-by-prefix comparison."},
    {"id": "CW-158", "language": "python", "description": "Read a YAML file into a dict", "implementation": "import yaml\ndef load_yaml(path: str) -> dict:\n    with open(path) as f:\n        return yaml.safe_load(f)", "explanation": "yaml.safe_load (NOT yaml.load) restricts deserialisation to standard YAML types — protects against the !!python/object code-execution attack (CVE-2017-18342). Use safe_load for ALL untrusted YAML. ruamel.yaml is the modern fork with round-trip preservation."},
    {"id": "CW-159", "language": "python", "description": "Run a function periodically with a background thread", "implementation": "import threading, time\ndef every(seconds: float, fn, stop_event: threading.Event):\n    def loop():\n        while not stop_event.is_set():\n            try: fn()\n            except Exception as e: print('error:', e)\n            stop_event.wait(seconds)\n    t = threading.Thread(target=loop, daemon=True)\n    t.start()\n    return t", "explanation": "Daemon thread terminates when the main process exits. Event.wait(seconds) is interruptible — setting the event causes immediate wake-up. Catches exceptions so one failure doesn't kill the loop. For richer scheduling use APScheduler or schedule library."},
    {"id": "CW-160", "language": "python", "description": "Validate a config dict with pydantic", "implementation": "from pydantic import BaseModel, ValidationError\n\nclass DBConfig(BaseModel):\n    host: str\n    port: int = 5432\n    user: str\n    password: str\n\ndef load(d: dict) -> DBConfig:\n    try: return DBConfig.model_validate(d)\n    except ValidationError as e:\n        raise ValueError(f'bad config: {e}')", "explanation": "Pydantic validates types, applies defaults, and produces structured errors on mismatch. model_validate is the v2 API (was parse_obj in v1). For env-driven configs use pydantic-settings which reads env vars / .env files. Pydantic v2 validators are written in Rust — fast."},
]


def _append(bank: Path, patterns: list) -> int:
    if not bank.exists():
        print(f"[error] bank not found: {bank}", file=sys.stderr)
        return 0
    existing = set()
    with bank.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line: continue
            try: existing.add(json.loads(line).get("id"))
            except json.JSONDecodeError: pass
    appended = 0
    with bank.open("a", encoding="utf-8") as f:
        for p in patterns:
            if p["id"] in existing: continue
            f.write(json.dumps(p, ensure_ascii=False) + "\n")
            appended += 1
    return appended


def main() -> int:
    ce = _append(EXPLAIN, EXPLAIN_PATTERNS)
    cw = _append(WRITE, WRITE_PATTERNS)
    print(f"  code-explain: appended {ce}")
    print(f"  code-write:   appended {cw}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
