#!/usr/bin/env python3
"""Expand the v0.9.23 code-explain bank with 40 more patterns (v0.9.25).

Adds web framework / database / testing / advanced concurrency /
build-system / advanced algorithm patterns the original bank didn't
cover. Idempotent: re-running skips IDs already present.

Each new pattern adds 5 records (one per variant in synth_code_explain).
40 new patterns -> 200 new records when synth is re-run.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BANK = REPO_ROOT / "data" / "raw" / "code_explain_patterns.jsonl"


NEW_PATTERNS = [
    # ---- Web frameworks --------------------------------------------------
    {"id": "CE-041", "language": "python", "snippet": "from flask import Flask, jsonify\napp = Flask(__name__)\n\n@app.get('/users/<int:user_id>')\ndef get_user(user_id):\n    return jsonify({'id': user_id, 'name': 'Alice'})\n\nif __name__ == '__main__':\n    app.run(debug=True, port=5000)", "purpose": "Minimal Flask REST endpoint with type-converted path parameter", "explanation": "Flask's `<int:user_id>` converter parses the URL segment as int and rejects non-int values with a 404. jsonify wraps the dict as a JSON response with the right Content-Type. debug=True enables auto-reload + interactive tracebacks (never use in production — it allows arbitrary code execution via the debugger console).", "key_concepts": ["Flask routing", "path converters", "JSON response", "debug mode caveat"]},
    {"id": "CE-042", "language": "python", "snippet": "from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\nclass User(BaseModel):\n    name: str\n    email: str\n\n@app.post('/users')\ndef create_user(user: User):\n    return {'created': user.name, 'email': user.email}", "purpose": "FastAPI POST endpoint with Pydantic validation", "explanation": "Pydantic models validate the request body against a typed schema; if email is missing or types are wrong, FastAPI returns a 422 with a structured error. The endpoint receives a fully typed User instance. FastAPI auto-generates OpenAPI docs from the type hints. Performance: as fast as Node-equivalents because Pydantic v2 validators are written in Rust.", "key_concepts": ["FastAPI", "Pydantic validation", "type hints as schema", "automatic OpenAPI"]},
    {"id": "CE-043", "language": "javascript", "snippet": "const express = require('express');\nconst app = express();\napp.use(express.json());\n\napp.post('/users', (req, res) => {\n  const { name, email } = req.body;\n  if (!name || !email) return res.status(400).json({ error: 'missing fields' });\n  res.status(201).json({ name, email });\n});\n\napp.listen(3000);", "purpose": "Express POST endpoint with JSON body parsing and validation", "explanation": "express.json() middleware parses JSON request bodies into req.body. Destructuring + truthiness check is the minimal validation; for richer schemas use Joi, Yup, or Zod. Status codes: 201 for created, 400 for client errors. .listen binds the port and starts the server.", "key_concepts": ["Express middleware", "request body parsing", "destructuring validation", "HTTP status codes"]},
    {"id": "CE-044", "language": "go", "snippet": "package main\n\nimport (\n    \"encoding/json\"\n    \"net/http\"\n)\n\ntype User struct {\n    Name  string `json:\"name\"`\n    Email string `json:\"email\"`\n}\n\nfunc main() {\n    http.HandleFunc(\"/users\", func(w http.ResponseWriter, r *http.Request) {\n        var u User\n        if err := json.NewDecoder(r.Body).Decode(&u); err != nil {\n            http.Error(w, err.Error(), http.StatusBadRequest)\n            return\n        }\n        w.Header().Set(\"Content-Type\", \"application/json\")\n        json.NewEncoder(w).Encode(u)\n    })\n    http.ListenAndServe(\":8080\", nil)\n}", "purpose": "Go HTTP handler with struct-tag-driven JSON decoding", "explanation": "Struct tags on User control how json.Decoder maps fields. Decode reads the request body and populates the struct; on parse error, return 400. Encode writes the struct as JSON. Set the Content-Type header before writing the body. For larger services, use chi or gin instead of net/http directly.", "key_concepts": ["struct tags for JSON", "decoder/encoder", "HTTP error handling"]},
    # ---- Database --------------------------------------------------------
    {"id": "CE-045", "language": "python", "snippet": "from sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base, sessionmaker\n\nBase = declarative_base()\nclass User(Base):\n    __tablename__ = 'users'\n    id = Column(Integer, primary_key=True)\n    name = Column(String, nullable=False)\n\nengine = create_engine('sqlite:///app.db')\nBase.metadata.create_all(engine)\nSession = sessionmaker(bind=engine)\nwith Session() as session:\n    session.add(User(name='Alice'))\n    session.commit()", "purpose": "SQLAlchemy ORM: declare schema, create tables, insert a row", "explanation": "declarative_base gives you a base class that maps subclasses to tables via class attributes. create_all issues CREATE TABLE for any tables not yet present. The Session is a unit of work; commit flushes pending changes. The `with` block manages session lifetime cleanly. Use Session.begin() for explicit transactions; SQLAlchemy auto-begins one on first use.", "key_concepts": ["ORM", "declarative mapping", "session as unit of work"]},
    {"id": "CE-046", "language": "python", "snippet": "import sqlite3\n\nconn = sqlite3.connect('app.db')\ncur = conn.cursor()\ncur.execute('SELECT id, name FROM users WHERE active = ?', (1,))\nfor row in cur.fetchall():\n    print(row)\nconn.close()", "purpose": "Raw SQL via sqlite3 with parameterised query", "explanation": "Parameter substitution via `?` placeholders prevents SQL injection — never f-string or % into the query text. fetchall returns all rows; for large results use the cursor as an iterator (`for row in cur:`) to stream. Always close the connection (or use it as a context manager).", "key_concepts": ["parameterised queries", "SQL injection prevention", "cursor as iterator"]},
    {"id": "CE-047", "language": "javascript", "snippet": "const { Pool } = require('pg');\nconst pool = new Pool({ connectionString: process.env.DATABASE_URL });\n\nasync function getUser(id) {\n  const r = await pool.query(\n    'SELECT id, name FROM users WHERE id = $1',\n    [id]\n  );\n  return r.rows[0];\n}", "purpose": "PostgreSQL parameterised query via node-postgres connection pool", "explanation": "Pool reuses connections across queries — much faster than opening a new connection per request. `$1` is the PG-style positional parameter; the second array argument supplies values, escaped by the driver. r.rows is the result array. Always use parameter binding; never interpolate user input into the SQL string.", "key_concepts": ["connection pooling", "parameterised query", "async/await with DB"]},
    # ---- Testing ---------------------------------------------------------
    {"id": "CE-048", "language": "python", "snippet": "import pytest\n\n@pytest.fixture\ndef sample_user():\n    return {'id': 1, 'name': 'Alice'}\n\ndef test_user_has_name(sample_user):\n    assert sample_user['name'] == 'Alice'\n\n@pytest.mark.parametrize('n,expected', [(0, 0), (1, 1), (5, 5)])\ndef test_identity(n, expected):\n    assert n == expected", "purpose": "pytest fixtures + parametrised tests", "explanation": "Fixtures are functions decorated with @pytest.fixture; tests opt in by naming them as parameters. parametrize generates multiple test cases from the same function, each appearing in the test report independently. Failure messages include the parameter values, so debugging is precise. Replace setUp/tearDown unittest patterns with fixtures + scope='function'/'session'.", "key_concepts": ["pytest fixtures", "parametrize decorator", "table-driven tests"]},
    {"id": "CE-049", "language": "javascript", "snippet": "const { test, expect } = require('@jest/globals');\n\ntest('sum adds two numbers', () => {\n  expect(1 + 2).toBe(3);\n});\n\ntest.each([\n  [1, 1, 2],\n  [2, 3, 5],\n  [-1, 1, 0],\n])('add(%i, %i) = %i', (a, b, expected) => {\n  expect(a + b).toBe(expected);\n});", "purpose": "Jest test with table-driven test.each", "explanation": "test() defines a single test case with a name and a body that uses expect assertions. test.each takes a 2D array of cases and a name template (with %i / %s / %p placeholders). Each row becomes its own test in the report. Jest auto-discovers files matching *.test.js / *.spec.js.", "key_concepts": ["Jest", "expect matchers", "table-driven tests"]},
    {"id": "CE-050", "language": "go", "snippet": "package math\n\nimport \"testing\"\n\nfunc TestAdd(t *testing.T) {\n    cases := []struct{ a, b, want int }{\n        {1, 1, 2},\n        {0, 0, 0},\n        {-1, 1, 0},\n    }\n    for _, c := range cases {\n        if got := Add(c.a, c.b); got != c.want {\n            t.Errorf(\"Add(%d, %d) = %d, want %d\", c.a, c.b, got, c.want)\n        }\n    }\n}", "purpose": "Go table-driven test in the standard library testing framework", "explanation": "testing.T is passed to every Test* function. The struct slice + range loop is the canonical Go table-driven pattern; each case is one assertion. t.Errorf records a failure but continues running cases; t.Fatalf would stop the test. Run with `go test`. Subtests via t.Run('name', ...) give individual case names in the report.", "key_concepts": ["table-driven tests", "Go testing package", "Errorf vs Fatalf"]},
    # ---- Concurrency primitives -----------------------------------------
    {"id": "CE-051", "language": "python", "snippet": "import threading\n\ncounter = 0\nlock = threading.Lock()\n\ndef increment():\n    global counter\n    with lock:\n        counter += 1", "purpose": "Thread-safe counter using a Lock as a context manager", "explanation": "Without the lock, `counter += 1` is read-modify-write across multiple bytecodes; threads can interleave and lose increments. The `with lock:` block acquires on entry and releases on exit, even on exception. Python's GIL doesn't save you here — the GIL switches mid-statement. For pure counters, threading.atomic counters (in newer pythons) or queue.Queue are alternatives.", "key_concepts": ["thread synchronization", "Lock as context manager", "race condition", "GIL doesn't help"]},
    {"id": "CE-052", "language": "go", "snippet": "import \"sync\"\n\nvar (\n    mu      sync.Mutex\n    counter int\n)\n\nfunc increment() {\n    mu.Lock()\n    defer mu.Unlock()\n    counter++\n}", "purpose": "Mutex-protected counter in Go", "explanation": "sync.Mutex provides Lock/Unlock. defer Unlock guarantees release even if the function panics. counter++ is now serialized across goroutines. Alternative for atomic counters: sync/atomic.AddInt64. RWMutex (sync.RWMutex) allows many readers OR one writer, useful when reads dominate.", "key_concepts": ["Mutex", "defer for release", "atomic vs mutex"]},
    {"id": "CE-053", "language": "python", "snippet": "import threading\n\nsemaphore = threading.Semaphore(3)\n\ndef download(url):\n    with semaphore:\n        # only 3 downloads run concurrently\n        do_download(url)", "purpose": "Semaphore to bound concurrency", "explanation": "Semaphore(3) lets up to 3 threads through at once. A Semaphore is essentially a counter: acquire decrements (blocking if zero), release increments. Useful for rate-limiting downstream calls (DB connections, third-party APIs, file handles). For asyncio, use asyncio.Semaphore. For Lock semantics with N=1, just use a Lock.", "key_concepts": ["Semaphore", "bounded concurrency", "rate limiting"]},
    {"id": "CE-054", "language": "rust", "snippet": "use std::sync::Mutex;\nuse std::sync::Arc;\nuse std::thread;\n\nfn main() {\n    let counter = Arc::new(Mutex::new(0));\n    let mut handles = vec![];\n    for _ in 0..10 {\n        let c = Arc::clone(&counter);\n        handles.push(thread::spawn(move || {\n            *c.lock().unwrap() += 1;\n        }));\n    }\n    for h in handles { h.join().unwrap(); }\n}", "purpose": "Rust thread-safe counter with Arc + Mutex", "explanation": "Arc (Atomically Reference-Counted) lets multiple threads own the same value; Mutex provides exclusive access. lock() returns Result; .unwrap() panics on poisoned lock. The deref `*c.lock()...` unwraps the MutexGuard. join waits for each thread. Cleaner than C++/Python equivalents because the borrow checker forces you to acknowledge sharing.", "key_concepts": ["Arc for shared ownership", "Mutex for exclusion", "thread spawn + join"]},
    # ---- More patterns + algorithms -------------------------------------
    {"id": "CE-055", "language": "python", "snippet": "class StateMachine:\n    def __init__(self):\n        self.state = 'idle'\n        self.transitions = {\n            ('idle', 'start'): 'running',\n            ('running', 'pause'): 'paused',\n            ('running', 'stop'): 'idle',\n            ('paused', 'resume'): 'running',\n        }\n    def fire(self, event):\n        key = (self.state, event)\n        if key in self.transitions:\n            self.state = self.transitions[key]\n        else:\n            raise ValueError(f'invalid event {event} in state {self.state}')", "purpose": "Tiny finite state machine driven by a transition table", "explanation": "Keys are (current_state, event), values are next_state. Compact, readable, easy to extend. For richer needs (entry/exit actions, hierarchical states, guards), use the `transitions` library. The pattern shines when the state graph is large enough to be confusing as nested if/elif but small enough to keep in one table.", "key_concepts": ["state machine", "transition table", "discrete events"]},
    {"id": "CE-056", "language": "python", "snippet": "def union_find_find(parent, x):\n    while parent[x] != x:\n        parent[x] = parent[parent[x]]  # path compression\n        x = parent[x]\n    return x\n\ndef union_find_union(parent, rank, x, y):\n    rx, ry = union_find_find(parent, x), union_find_find(parent, y)\n    if rx == ry: return\n    if rank[rx] < rank[ry]: rx, ry = ry, rx\n    parent[ry] = rx\n    if rank[rx] == rank[ry]: rank[rx] += 1", "purpose": "Union-Find (Disjoint Set Union) with path compression and union by rank", "explanation": "find returns the representative of x's set, flattening the tree along the way (path compression). union merges two sets, attaching the shorter tree under the taller (union by rank). Both operations have nearly-O(1) amortised complexity (technically O(α(n)), the inverse Ackermann function). Used in Kruskal's MST, connected-components, image segmentation, equivalence-class problems.", "key_concepts": ["disjoint set union", "path compression", "union by rank", "amortised analysis"]},
    {"id": "CE-057", "language": "python", "snippet": "def kmp_table(p):\n    t = [0] * len(p)\n    k = 0\n    for i in range(1, len(p)):\n        while k > 0 and p[k] != p[i]:\n            k = t[k - 1]\n        if p[k] == p[i]:\n            k += 1\n        t[i] = k\n    return t\n\ndef kmp_search(s, p):\n    t = kmp_table(p)\n    k = 0\n    for i, c in enumerate(s):\n        while k > 0 and p[k] != c:\n            k = t[k - 1]\n        if p[k] == c:\n            k += 1\n        if k == len(p):\n            return i - k + 1\n    return -1", "purpose": "Knuth-Morris-Pratt string search", "explanation": "Builds a failure table that, when a mismatch occurs at position k in the pattern, tells you how far to slide the pattern without re-scanning text. Result: O(n + m) total time, where n is text length and m is pattern length. The naive search is O(n*m). Foundation of many string algorithms; modern equivalents (Boyer-Moore, Aho-Corasick) extend the same idea.", "key_concepts": ["KMP failure function", "string matching", "linear-time search"]},
    {"id": "CE-058", "language": "python", "snippet": "import heapq\n\ndef dijkstra(graph, start):\n    dist = {n: float('inf') for n in graph}\n    dist[start] = 0\n    pq = [(0, start)]\n    while pq:\n        d, u = heapq.heappop(pq)\n        if d > dist[u]:\n            continue\n        for v, w in graph[u].items():\n            new = d + w\n            if new < dist[v]:\n                dist[v] = new\n                heapq.heappush(pq, (new, v))\n    return dist", "purpose": "Dijkstra's shortest-path algorithm with a binary heap", "explanation": "Pops the smallest-distance node, relaxes its outgoing edges, pushes updated targets. The 'if d > dist[u]: continue' check skips stale heap entries (we lazy-delete by inserting new ones). O((V + E) log V) with binary heap. Requires non-negative edge weights; for negative weights use Bellman-Ford. For dense graphs, the array variant (no heap) is O(V^2) and faster in constant.", "key_concepts": ["shortest paths", "priority queue", "edge relaxation", "lazy deletion"]},
    # ---- Build / tooling -----------------------------------------------
    {"id": "CE-059", "language": "shell", "snippet": "#!/bin/bash\nset -euo pipefail\n\nfor f in *.log; do\n    [[ -f $f ]] || continue\n    grep ERROR \"$f\" || true\ndone", "purpose": "Bash script that greps ERROR from every .log file, robust to no-match", "explanation": "set -euo pipefail makes bash actually safe: -e exit on any error, -u error on unset vars, -o pipefail propagates pipe failures. The `[[ -f $f ]] || continue` skips when the glob doesn't match (which leaves $f as the literal '*.log'). `|| true` prevents grep's exit code 1 (no match) from killing the script under -e.", "key_concepts": ["bash safety flags", "set -euo pipefail", "glob handling", "grep exit code"]},
    {"id": "CE-060", "language": "shell", "snippet": "#!/bin/bash\nset -e\nimage=\"myapp:$(git rev-parse --short HEAD)\"\ndocker build -t \"$image\" .\ndocker push \"$image\"\nkubectl set image deployment/myapp app=\"$image\"", "purpose": "Build, push, and deploy a Docker image tagged by git commit", "explanation": "Tags the image with the short SHA so each build has a unique, reproducible identifier (no 'latest' confusion). `set -e` aborts on any error; you don't want to push if the build fails or update the deployment if the push fails. kubectl set image triggers a rolling update.", "key_concepts": ["git SHA tagging", "rolling deployment", "fail-fast scripting"]},
    # ---- Advanced idioms ------------------------------------------------
    {"id": "CE-061", "language": "python", "snippet": "from abc import ABC, abstractmethod\n\nclass Storage(ABC):\n    @abstractmethod\n    def get(self, key: str) -> str: ...\n    @abstractmethod\n    def put(self, key: str, value: str) -> None: ...\n\nclass MemoryStorage(Storage):\n    def __init__(self):\n        self._d = {}\n    def get(self, key): return self._d[key]\n    def put(self, key, value): self._d[key] = value", "purpose": "Abstract Base Class defining a Storage interface", "explanation": "ABC + @abstractmethod enforces that subclasses implement the interface. Instantiating Storage() directly raises TypeError; only concrete subclasses (those that implement all abstract methods) can be constructed. Useful for plugin systems, dependency injection, contract definitions. typing.Protocol (PEP 544) provides structural typing without inheritance — choose ABC for nominal typing, Protocol for duck-typed interfaces.", "key_concepts": ["abstract base class", "interface", "abstractmethod"]},
    {"id": "CE-062", "language": "python", "snippet": "def sliding_window(iterable, n):\n    from collections import deque\n    it = iter(iterable)\n    window = deque(maxlen=n)\n    for item in it:\n        window.append(item)\n        if len(window) == n:\n            yield tuple(window)", "purpose": "Generator yielding sliding windows of size n over an iterable", "explanation": "deque with maxlen automatically drops old elements when full. The generator yields each full window as a tuple. Lazy: only one window in memory regardless of input size. itertools recipes have a similar `sliding_window` since Python 3.10 (`itertools.pairwise` is the n=2 case). Common in time-series moving averages, sequence preprocessing, n-gram extraction.", "key_concepts": ["generator", "deque with maxlen", "sliding window pattern"]},
    {"id": "CE-063", "language": "python", "snippet": "from contextlib import suppress\n\nwith suppress(FileNotFoundError):\n    os.remove('/tmp/maybe-here.txt')", "purpose": "Suppress a specific exception in a block without try/except", "explanation": "contextlib.suppress catches and ignores the named exception type(s) inside its block. Cleaner than `try: ...; except FileNotFoundError: pass` when the block is short. Be conservative — suppressing exceptions hides bugs. Multiple types: `suppress(FileNotFoundError, PermissionError)`.", "key_concepts": ["contextlib.suppress", "narrow exception handling"]},
    {"id": "CE-064", "language": "rust", "snippet": "fn divisible_by(n: i32) -> impl Fn(i32) -> bool {\n    move |x| x % n == 0\n}\n\nfn main() {\n    let div3 = divisible_by(3);\n    let nums: Vec<i32> = (1..=10).filter(|x| div3(*x)).collect();\n    // nums = [3, 6, 9]\n}", "purpose": "Higher-order function returning a closure that captures n", "explanation": "`impl Fn(i32) -> bool` is the unboxed return-type-impl-trait syntax (since Rust 1.26). `move` forces the closure to take ownership of n. The returned closure can be called like a regular function. For dynamically-sized closures stored in collections, use `Box<dyn Fn(i32) -> bool>`.", "key_concepts": ["closures", "impl trait return", "move closure", "higher-order functions"]},
    # ---- More algorithms -----------------------------------------------
    {"id": "CE-065", "language": "python", "snippet": "import heapq\n\ndef merge_k_sorted(lists):\n    heap = []\n    for i, lst in enumerate(lists):\n        if lst:\n            heap.append((lst[0], i, 0))\n    heapq.heapify(heap)\n    out = []\n    while heap:\n        val, list_idx, elem_idx = heapq.heappop(heap)\n        out.append(val)\n        if elem_idx + 1 < len(lists[list_idx]):\n            heapq.heappush(heap, (lists[list_idx][elem_idx + 1], list_idx, elem_idx + 1))\n    return out", "purpose": "Merge k sorted lists into one sorted output", "explanation": "Min-heap of size k holding the next candidate from each list. On each pop, advance the source list's pointer and push its next element. O(N log k) total where N is the total elements; beats merging pairwise (O(N k)). The (val, list_idx, elem_idx) tuple ensures stable ordering on ties — list_idx breaks the tie.", "key_concepts": ["k-way merge", "min-heap", "tie-breaking with index"]},
    {"id": "CE-066", "language": "python", "snippet": "def longest_increasing_subsequence(arr):\n    from bisect import bisect_left\n    tails = []\n    for x in arr:\n        i = bisect_left(tails, x)\n        if i == len(tails):\n            tails.append(x)\n        else:\n            tails[i] = x\n    return len(tails)", "purpose": "Length of longest strictly increasing subsequence in O(n log n)", "explanation": "tails[i] holds the smallest possible tail value of an LIS of length i+1 seen so far. For each new x, find where it fits via binary search; either extend (if larger than all tails) or replace the first tail >= x. Doesn't reconstruct the actual subsequence — for that, track parent pointers. The naive DP is O(n^2).", "key_concepts": ["longest increasing subsequence", "binary search", "patience sorting"]},
    # ---- More language features ----------------------------------------
    {"id": "CE-067", "language": "javascript", "snippet": "function* fib() {\n  let [a, b] = [0, 1];\n  while (true) {\n    yield a;\n    [a, b] = [b, a + b];\n  }\n}\n\nconst it = fib();\nconst first10 = [];\nfor (let i = 0; i < 10; i++) first10.push(it.next().value);", "purpose": "Generator function producing an infinite Fibonacci stream", "explanation": "function* declares a generator. yield pauses the function, returning the value to the caller; .next() resumes it. State (a, b) is preserved across calls. Infinite streams are safe because they're lazy — only the values you ask for are computed. Generators are the foundation of async/await; an async function is a generator that yields promises.", "key_concepts": ["generator function", "lazy infinite sequences", "yield"]},
    {"id": "CE-068", "language": "javascript", "snippet": "const config = Object.freeze({\n  apiUrl: 'https://api.example.com',\n  timeout: 5000,\n});\n\nconfig.apiUrl = 'evil.com';  // silently fails (or throws in strict mode)", "purpose": "Object.freeze creates a shallow-immutable object", "explanation": "Object.freeze makes existing top-level properties non-writable and non-configurable. Attempts to mutate fail silently in sloppy mode, throw in strict mode. Shallow only: nested objects can still be mutated. For deep immutability use Object.freeze recursively, or a library like Immutable.js. TypeScript's `as const` is a compile-time analogue.", "key_concepts": ["immutability", "Object.freeze", "shallow vs deep freezing"]},
    {"id": "CE-069", "language": "rust", "snippet": "#[derive(Debug, Clone, PartialEq)]\nstruct Point { x: f64, y: f64 }\n\nfn main() {\n    let p1 = Point { x: 1.0, y: 2.0 };\n    let p2 = p1.clone();\n    println!(\"{:?} == {:?}: {}\", p1, p2, p1 == p2);\n}", "purpose": "Auto-derive standard traits for a struct", "explanation": "#[derive(...)] generates implementations of common traits. Debug enables {:?} formatting, Clone enables .clone(), PartialEq enables ==. All work because each field type also implements them (f64 does). Eq, Hash, Ord, Default, Copy are other common derives. Custom logic requires manual impl. Macro hygiene + compile-time generation: zero cost at runtime.", "key_concepts": ["derive macros", "trait implementation", "Debug/Clone/PartialEq"]},
    # ---- Web / async / queues ------------------------------------------
    {"id": "CE-070", "language": "python", "snippet": "import asyncio\n\nasync def producer(q):\n    for i in range(5):\n        await q.put(i)\n        await asyncio.sleep(0.1)\n    await q.put(None)  # sentinel\n\nasync def consumer(q):\n    while True:\n        item = await q.get()\n        if item is None:\n            break\n        print(f'got {item}')\n\nasync def main():\n    q = asyncio.Queue()\n    await asyncio.gather(producer(q), consumer(q))\n\nasyncio.run(main())", "purpose": "Async producer/consumer using asyncio.Queue", "explanation": "asyncio.Queue is the async-safe analogue of queue.Queue. put and get are coroutines. The None sentinel signals end-of-stream to the consumer. asyncio.gather runs both coroutines concurrently on the same event loop. For backpressure, asyncio.Queue accepts a maxsize; put blocks when full.", "key_concepts": ["async producer-consumer", "asyncio.Queue", "sentinel pattern"]},
    {"id": "CE-071", "language": "python", "snippet": "import logging\nlogging.basicConfig(\n    level=logging.INFO,\n    format='%(asctime)s %(levelname)s %(name)s %(message)s',\n)\nlog = logging.getLogger(__name__)\nlog.info('app starting on port %d', 8000)\nlog.warning('low disk: %.1f GB free', 0.5)\nlog.exception('failed: %s', 'reason')  # call this inside except", "purpose": "Standard library logging setup", "explanation": "basicConfig configures the root logger; subsequent getLogger calls use it. Use lazy %-formatting (`'%s', x` rather than f-strings) so the args are only formatted if the level filters in. log.exception logs at ERROR with a stack trace; only meaningful inside an except block. For production, write JSON via structlog or log to a file with RotatingFileHandler.", "key_concepts": ["logging.basicConfig", "lazy formatting", "log.exception"]},
    # ---- File system / OS ----------------------------------------------
    {"id": "CE-072", "language": "python", "snippet": "from pathlib import Path\n\nfor py in Path('.').rglob('*.py'):\n    if 'tests' in py.parts:\n        continue\n    text = py.read_text()\n    if 'TODO' in text:\n        print(py)", "purpose": "Recursively find Python files containing TODO, excluding test directories", "explanation": "pathlib's Path is the modern way to handle filesystem paths. rglob is recursive glob. .parts splits the path into components for filtering. read_text reads the whole file; for huge files use open + iterate. The pattern is cleaner than os.walk + os.path.join + manual filtering.", "key_concepts": ["pathlib", "recursive glob", "path components", "Path.read_text"]},
    {"id": "CE-073", "language": "python", "snippet": "import subprocess\n\nresult = subprocess.run(\n    ['git', 'log', '--oneline', '-n', '5'],\n    capture_output=True,\n    text=True,\n    check=True,\n)\nfor line in result.stdout.splitlines():\n    print(line)", "purpose": "Run a subprocess and capture its stdout", "explanation": "subprocess.run is the high-level interface. Pass argv as a list (not a string) to avoid shell injection. capture_output=True captures both stdout + stderr. text=True decodes as UTF-8 (else bytes). check=True raises CalledProcessError on non-zero exit. For streaming output, use Popen + .stdout iteration.", "key_concepts": ["subprocess.run", "argv as list", "shell injection avoidance", "check=True"]},
    # ---- Functional + data ---------------------------------------------
    {"id": "CE-074", "language": "python", "snippet": "from functools import reduce\nfrom operator import mul\n\ndef product(nums):\n    return reduce(mul, nums, 1)", "purpose": "Reduce a list to its product using functools.reduce", "explanation": "reduce applies a binary function cumulatively across the iterable, starting from an initial value. mul is operator.mul = lambda a, b: a*b. The initial 1 is the multiplicative identity, ensuring product([]) = 1. Python 3.8+ has math.prod which is faster and clearer for this specific use. reduce is general; prod is special-purpose.", "key_concepts": ["reduce / fold", "operator module", "identity element"]},
    {"id": "CE-075", "language": "python", "snippet": "from itertools import groupby\n\nrows = [\n    {'team': 'A', 'name': 'Alice'},\n    {'team': 'A', 'name': 'Bob'},\n    {'team': 'B', 'name': 'Carol'},\n]\nrows.sort(key=lambda r: r['team'])\nfor team, group in groupby(rows, key=lambda r: r['team']):\n    names = [r['name'] for r in group]\n    print(team, names)", "purpose": "itertools.groupby clusters consecutive equal-key items", "explanation": "Critical caveat: groupby only groups CONSECUTIVE matches, so you must sort first by the same key. The output is (key, iterator) pairs; the iterator is single-pass (consume it before the next iteration). Same shape as SQL GROUP BY conceptually but applied to in-memory iterables.", "key_concepts": ["itertools.groupby", "must sort first", "iterator-yielding pattern"]},
    # ---- Errors + edge cases -------------------------------------------
    {"id": "CE-076", "language": "python", "snippet": "class TimeoutError(Exception):\n    pass\n\nclass NetworkError(Exception):\n    def __init__(self, host: str, port: int, msg: str):\n        super().__init__(f'{host}:{port}: {msg}')\n        self.host = host\n        self.port = port\n\ntry:\n    raise NetworkError('example.com', 443, 'connection refused') from OSError('ECONNREFUSED')\nexcept NetworkError as e:\n    print(e.host, e.__cause__)", "purpose": "Custom exceptions with structured fields and exception chaining", "explanation": "Subclass Exception (or a more specific built-in) to define custom errors. Storing host/port as attributes lets callers inspect them programmatically. `raise X from Y` sets __cause__ and prints both tracebacks; preserves the lower-level cause without losing the higher-level context. Use `from None` to suppress the cause chain.", "key_concepts": ["custom exceptions", "exception chaining", "raise from"]},
    {"id": "CE-077", "language": "go", "snippet": "type NotFoundError struct {\n    Key string\n}\n\nfunc (e *NotFoundError) Error() string {\n    return fmt.Sprintf(\"not found: %s\", e.Key)\n}\n\nfunc lookup(key string) (string, error) {\n    return \"\", &NotFoundError{Key: key}\n}\n\nfunc main() {\n    _, err := lookup(\"foo\")\n    var nf *NotFoundError\n    if errors.As(err, &nf) {\n        fmt.Println(\"key was:\", nf.Key)\n    }\n}", "purpose": "Custom error type with errors.As for typed extraction", "explanation": "Define an error type by implementing Error() string. errors.As walks the error wrapping chain looking for the target type, populating the pointer if found. errors.Is checks for sentinel-error equality. Together these replace the older type-assertion + comparison patterns. fmt.Errorf with %w wraps an error; the wrapped error becomes part of the chain.", "key_concepts": ["custom error type", "errors.As / errors.Is", "error wrapping with %w"]},
    # ---- Performance + memory ------------------------------------------
    {"id": "CE-078", "language": "python", "snippet": "import sys\nx = [1, 2, 3]\nprint(sys.getsizeof(x))\nprint([sys.getsizeof(i) for i in x])", "purpose": "Inspect Python object memory size", "explanation": "sys.getsizeof returns the bytes used by the object, NOT including any objects it references. So a list's size includes its overhead and pointers, not the int values. For deep size, use a recursive walk or the `pympler` library. CPython int memory is ~28 bytes per number, much more than C int. NumPy arrays pack values densely.", "key_concepts": ["sys.getsizeof", "shallow vs deep size", "Python object overhead"]},
    {"id": "CE-079", "language": "python", "snippet": "import cProfile, pstats\n\ndef expensive():\n    return sum(i*i for i in range(1_000_000))\n\nwith cProfile.Profile() as pr:\n    expensive()\nstats = pstats.Stats(pr).sort_stats('cumulative')\nstats.print_stats(10)", "purpose": "Profile a function with cProfile", "explanation": "cProfile records every function call, arg counts, time. Sort by cumulative time to find the heavy hitters. For line-level profiling, use line_profiler. For sampling profilers (lower overhead, runs in production), py-spy or scalene. Never optimise without profiling — your guess about where time is spent is usually wrong.", "key_concepts": ["cProfile", "pstats", "cumulative vs total time"]},
    {"id": "CE-080", "language": "javascript", "snippet": "performance.mark('start');\nfor (let i = 0; i < 1_000_000; i++) {\n  Math.sqrt(i);\n}\nperformance.mark('end');\nperformance.measure('sqrt-loop', 'start', 'end');\nconst entries = performance.getEntriesByName('sqrt-loop');\nconsole.log(entries[0].duration, 'ms');", "purpose": "Browser Performance API timing", "explanation": "performance.mark stamps a named time, performance.measure computes the duration between two marks. Available in browsers and Node. Sub-millisecond precision (0.5ms in browsers, microseconds in Node). For single-shot timings, performance.now() is enough. The PerformanceObserver pattern lets you collect entries without polling.", "key_concepts": ["Performance API", "marks and measures", "high-resolution timing"]},
]


def main() -> int:
    if not BANK.exists():
        print(f"[error] bank not found: {BANK}", file=sys.stderr)
        return 1
    existing_ids = set()
    with BANK.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            existing_ids.add(rec.get("id"))
    print(f"  Existing patterns: {len(existing_ids)}")

    appended = 0
    with BANK.open("a", encoding="utf-8") as f:
        for p in NEW_PATTERNS:
            if p["id"] in existing_ids:
                continue
            f.write(json.dumps(p, ensure_ascii=False) + "\n")
            appended += 1
    print(f"  Appended:          {appended}")
    print(f"  Total now:         {len(existing_ids) + appended}")
    print()
    print("Re-run synth to produce updated SFT corpus:")
    print("  PYTHONPATH=. python3 scripts/synth_code_explain.py \\")
    print("      --bank data/raw/code_explain_patterns.jsonl \\")
    print("      --out data/processed/synth_code_explain.jsonl")
    return 0


if __name__ == "__main__":
    sys.exit(main())
