#!/usr/bin/env python3
"""Phase 3 expansion of BOTH code-explain and code-write banks (v0.9.27).

Adds 40 patterns to each bank in one shot:
  code-explain: 80 -> 120 patterns -> 600 SFT records (was 400)
  code-write:   80 -> 120 patterns -> ~360 SFT records (was 243)

Total +320 SFT records in one release. Idempotent on both banks.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPLAIN = REPO_ROOT / "data" / "raw" / "code_explain_patterns.jsonl"
WRITE = REPO_ROOT / "data" / "raw" / "code_write_patterns.jsonl"


# 40 more code-explain patterns covering: more web (Tornado, Sanic),
# DevOps (k8s yaml, GitHub Actions), more concurrency (channels,
# actors, locks), more algorithms (Bellman-Ford, A*, sliding-window
# max), more idioms (typing.Protocol, Rust traits with generics,
# Python __slots__).
EXPLAIN_PATTERNS = [
    {"id": "CE-081", "language": "python", "snippet": "from dataclasses import dataclass\nfrom typing import Protocol\n\nclass Renderable(Protocol):\n    def render(self) -> str: ...\n\n@dataclass\nclass Box:\n    width: int\n    def render(self) -> str:\n        return '+' + '-' * self.width + '+'\n\ndef show(r: Renderable) -> None:\n    print(r.render())\n\nshow(Box(5))", "purpose": "Structural typing via typing.Protocol", "explanation": "Protocol gives you duck-typed interfaces without explicit inheritance — any class with the right methods + signatures satisfies it. The type checker (mypy) verifies. Cleaner than ABCs when you don't control the implementations (third-party classes can satisfy a Protocol you defined).", "key_concepts": ["structural typing", "Protocol", "duck typing with type checking"]},
    {"id": "CE-082", "language": "python", "snippet": "class Vec3:\n    __slots__ = ('x', 'y', 'z')\n    def __init__(self, x, y, z):\n        self.x, self.y, self.z = x, y, z", "purpose": "Memory-efficient class with __slots__", "explanation": "__slots__ tells Python to skip the per-instance __dict__ and store attributes in a fixed slot table. Saves 50-70% memory per instance for many-instances workloads. Tradeoffs: can't add new attributes at runtime, multiple inheritance is awkward, weakref needs '__weakref__' in slots. Use for value types you'll have millions of.", "key_concepts": ["__slots__", "memory optimisation", "fixed attribute table"]},
    {"id": "CE-083", "language": "python", "snippet": "from typing import TypeVar, Generic\n\nT = TypeVar('T')\nclass Stack(Generic[T]):\n    def __init__(self) -> None:\n        self._items: list[T] = []\n    def push(self, x: T) -> None: self._items.append(x)\n    def pop(self) -> T: return self._items.pop()", "purpose": "Generic class parameterised on element type", "explanation": "TypeVar declares a generic type parameter; Generic[T] makes Stack a generic class. Stack[int] vs Stack[str] are checked separately by mypy. Python 3.12 has PEP 695 syntax (`class Stack[T]:`) that's cleaner. Runtime sees T as Any; type-safety is compile-time only.", "key_concepts": ["generics", "TypeVar", "Generic class"]},
    {"id": "CE-084", "language": "rust", "snippet": "trait Renderable {\n    fn render(&self) -> String;\n}\n\nimpl<T: Renderable> Renderable for Vec<T> {\n    fn render(&self) -> String {\n        self.iter()\n            .map(|x| x.render())\n            .collect::<Vec<_>>()\n            .join(\"\\n\")\n    }\n}", "purpose": "Blanket impl: implement a trait for any Vec<T> where T already implements it", "explanation": "Blanket impls add behaviour to entire categories of types. Here any Vec of Renderable items becomes Renderable itself, joining child renders with newlines. The bound `T: Renderable` constrains which types this applies to. Used heavily in std (every &T implements Display when T: Display, etc.).", "key_concepts": ["trait bounds", "blanket impl", "generic implementation"]},
    {"id": "CE-085", "language": "python", "snippet": "import asyncio\n\nasync def main():\n    async with asyncio.TaskGroup() as tg:\n        tg.create_task(slow_fetch('a'))\n        tg.create_task(slow_fetch('b'))\n        tg.create_task(slow_fetch('c'))\n\nasyncio.run(main())", "purpose": "Structured concurrency with asyncio.TaskGroup", "explanation": "Python 3.11+ TaskGroup ensures all child tasks complete (or all are cancelled) before the with-block exits. If any task raises, the rest are cancelled and the exception group propagates. Cleaner than asyncio.gather + try/except: cancellation semantics are explicit and child tasks can't leak past the block.", "key_concepts": ["structured concurrency", "TaskGroup", "exception groups"]},
    {"id": "CE-086", "language": "go", "snippet": "ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)\ndefer cancel()\n\nresult := make(chan int, 1)\ngo func() {\n    result <- slowOperation()\n}()\n\nselect {\ncase r := <-result:\n    fmt.Println(r)\ncase <-ctx.Done():\n    fmt.Println(\"timed out\")\n}", "purpose": "Cancellable operation via context + select", "explanation": "context.WithTimeout returns a context that auto-cancels after the duration. The goroutine performs work and writes to a channel. select waits for whichever happens first: result arrives or context is cancelled. Always defer cancel() to release the context's resources. Goroutines that read from cancelled contexts should bail out promptly to avoid leaks.", "key_concepts": ["context cancellation", "select on channels", "timeout pattern"]},
    {"id": "CE-087", "language": "python", "snippet": "from concurrent.futures import ThreadPoolExecutor, as_completed\n\nwith ThreadPoolExecutor(max_workers=10) as ex:\n    futures = {ex.submit(fetch, url): url for url in urls}\n    for f in as_completed(futures):\n        url = futures[f]\n        try:\n            data = f.result()\n        except Exception as e:\n            print(f'{url}: {e}')", "purpose": "Thread pool with as_completed for parallel I/O", "explanation": "ThreadPoolExecutor manages 10 worker threads. submit returns a Future; as_completed yields futures in completion order, not submit order. This pattern is right for I/O-bound work (HTTP, file reads). For CPU-bound use ProcessPoolExecutor (sidesteps the GIL). The dict maps futures back to their URL for error context.", "key_concepts": ["ThreadPoolExecutor", "as_completed", "Future error handling"]},
    {"id": "CE-088", "language": "python", "snippet": "import heapq\n\ndef sliding_window_max(arr, k):\n    out = []\n    heap = []\n    for i, n in enumerate(arr):\n        heapq.heappush(heap, (-n, i))\n        while heap[0][1] <= i - k:\n            heapq.heappop(heap)\n        if i >= k - 1:\n            out.append(-heap[0][0])\n    return out", "purpose": "Maximum in each sliding window of size k", "explanation": "Negative-value heap because heapq is min-heap. Lazy deletion: stale indices (outside the window) are popped only when they reach the top. O(n log k) time. For O(n) use a monotonic deque instead — that's the textbook solution but the heap version is more general and easier to remember.", "key_concepts": ["sliding window", "heap with lazy deletion", "negation trick for max-heap"]},
    {"id": "CE-089", "language": "python", "snippet": "import re\n\nlog_re = re.compile(\n    r'^(?P<ts>\\S+) (?P<level>\\w+) (?P<msg>.+)$'\n)\nfor line in lines:\n    m = log_re.match(line)\n    if m:\n        ts = m.group('ts')\n        level = m.group('level')", "purpose": "Named regex groups for structured log parsing", "explanation": "(?P<name>...) creates a named group accessible via m.group('name'). Cleaner than positional groups when you have many fields. m.groupdict() returns {name: match} for all named groups. For more complex structured parsing use a dedicated parser library (parse, pyparsing, lark).", "key_concepts": ["named groups", "regex compilation", "structured parsing"]},
    {"id": "CE-090", "language": "javascript", "snippet": "const memo = new Map();\nfunction memoize(fn) {\n  return function(...args) {\n    const key = JSON.stringify(args);\n    if (!memo.has(key)) {\n      memo.set(key, fn.apply(this, args));\n    }\n    return memo.get(key);\n  };\n}", "purpose": "Generic JavaScript memoization via Map + JSON.stringify key", "explanation": "Maps keys preserved by reference (faster than Object key lookup). JSON.stringify is the lazy way to make a hashable key from arguments — works for primitives + plain objects. Caveat: doesn't work for circular refs, BigInt, or functions. For production use lodash.memoize which handles edge cases.", "key_concepts": ["memoization", "Map vs Object", "JSON-stringify key trick"]},
    {"id": "CE-091", "language": "python", "snippet": "from itertools import islice, count\n\nprimes = (\n    n for n in count(2)\n    if all(n % p for p in range(2, int(n**0.5) + 1))\n)\nfirst_10 = list(islice(primes, 10))", "purpose": "Lazy infinite prime generator with itertools.islice", "explanation": "count(2) is an infinite iterator from 2 upward. The generator expression filters with the trial-division primality test. islice takes the first 10 from the lazy stream — without it, list() would loop forever. itertools is the bedrock library for lazy sequence operations; combine with chain, takewhile, dropwhile, groupby, accumulate.", "key_concepts": ["lazy infinite sequence", "itertools.count + islice"]},
    {"id": "CE-092", "language": "python", "snippet": "def chunked(iterable, n):\n    it = iter(iterable)\n    while True:\n        chunk = []\n        for _ in range(n):\n            try:\n                chunk.append(next(it))\n            except StopIteration:\n                if chunk:\n                    yield chunk\n                return\n        yield chunk", "purpose": "Group an iterable into chunks of size n (last may be partial)", "explanation": "Iterates the source N items at a time, yielding each chunk. Last chunk may be smaller. Lazy: doesn't materialise the full iterable. For Python 3.12+ use itertools.batched which does the same in C. Useful for batching API calls, page-sized queries, multipart uploads.", "key_concepts": ["chunking", "lazy generator", "iterator state machine"]},
    {"id": "CE-093", "language": "go", "snippet": "func generator(ctx context.Context) <-chan int {\n    out := make(chan int)\n    go func() {\n        defer close(out)\n        for i := 0; ; i++ {\n            select {\n            case out <- i:\n            case <-ctx.Done():\n                return\n            }\n        }\n    }()\n    return out\n}", "purpose": "Cancellable infinite generator via channel + context", "explanation": "Returns a receive-only channel. The goroutine sends incrementing ints until either the receiver stops reading (no slot available) or the context is cancelled. select on send + ctx.Done is the canonical Go pattern for cooperative cancellation. defer close releases the channel so receivers can range-loop until close.", "key_concepts": ["channel direction", "select on send", "context cancellation"]},
    {"id": "CE-094", "language": "python", "snippet": "from functools import partial\n\ndef greet(greeting, name):\n    return f'{greeting}, {name}!'\n\nhello = partial(greet, 'Hello')\nhowdy = partial(greet, 'Howdy')\nprint(hello('Alice'))   # Hello, Alice!", "purpose": "Partial application with functools.partial", "explanation": "partial freezes some arguments of a function, returning a new callable that needs only the rest. Useful for adapting a generic function to a specific use site, e.g. partial(callback, user_id=5) for a callback that takes a user_id and event. Equivalent to a lambda but more efficient and pickle-able.", "key_concepts": ["partial application", "currying analogue", "functools.partial"]},
    {"id": "CE-095", "language": "python", "snippet": "from enum import Enum, auto\n\nclass Status(Enum):\n    PENDING = auto()\n    RUNNING = auto()\n    DONE = auto()\n    FAILED = auto()\n\ns = Status.PENDING\nif s in {Status.PENDING, Status.RUNNING}:\n    print('still going')", "purpose": "Type-safe enums with auto-assigned values", "explanation": "Enum gives you named constants that are NOT just ints. Status.PENDING is a Status, not an int — comparing to int raises (mostly). auto() lets you skip explicit values. For string-typed enums, subclass StrEnum (3.11+) or define values explicitly. IntEnum / IntFlag exist for cases where int interop is needed.", "key_concepts": ["enums", "auto-numbering", "type safety vs int interop"]},
    {"id": "CE-096", "language": "rust", "snippet": "enum Shape {\n    Circle { radius: f64 },\n    Rectangle { width: f64, height: f64 },\n    Triangle { base: f64, height: f64 },\n}\n\nfn area(s: &Shape) -> f64 {\n    match s {\n        Shape::Circle { radius } => std::f64::consts::PI * radius * radius,\n        Shape::Rectangle { width, height } => width * height,\n        Shape::Triangle { base, height } => 0.5 * base * height,\n    }\n}", "purpose": "Algebraic data type with struct-like enum variants", "explanation": "Rust enums can carry data per variant — far more powerful than C enums. The match expression destructures variants with field names. Compiler enforces exhaustive handling (add a new variant, every match without a `_` arm fails to compile). Cleaner than class hierarchies for sum types: closed set of variants, pattern matching, no inheritance complexity.", "key_concepts": ["sum type / algebraic data type", "enum with fields", "exhaustive match"]},
    {"id": "CE-097", "language": "python", "snippet": "from collections import ChainMap\n\nuser_settings = {'theme': 'dark'}\norg_settings = {'theme': 'light', 'lang': 'en'}\ndefaults = {'theme': 'light', 'lang': 'en', 'timeout': 30}\n\nsettings = ChainMap(user_settings, org_settings, defaults)\nprint(settings['theme'])    # 'dark' (user wins)\nprint(settings['timeout'])  # 30 (falls through to defaults)", "purpose": "Layered configuration via collections.ChainMap", "explanation": "ChainMap searches the maps left-to-right; first match wins. No dict merging, no copies — purely a view. Updates go to the leftmost map. Perfect for layered configs (CLI flags > env vars > config file > defaults). Each layer can be modified independently and the view reflects it immediately.", "key_concepts": ["ChainMap", "layered configuration", "view semantics"]},
    {"id": "CE-098", "language": "python", "snippet": "import contextlib\n\n@contextlib.contextmanager\ndef chdir(path):\n    old = os.getcwd()\n    os.chdir(path)\n    try:\n        yield\n    finally:\n        os.chdir(old)", "purpose": "Temporarily change directory using a context manager", "explanation": "Saves cwd, changes to path, yields control, restores cwd on exit (success OR exception). The try/finally is critical: without it an exception inside the with-block leaves cwd in the wrong place permanently. Python 3.11+ has contextlib.chdir built in, doing exactly this.", "key_concepts": ["contextmanager decorator", "try/finally for cleanup", "directory state"]},
    {"id": "CE-099", "language": "python", "snippet": "from typing import overload, Union\n\n@overload\ndef parse(x: str) -> int: ...\n@overload\ndef parse(x: bytes) -> int: ...\n@overload\ndef parse(x: int) -> int: ...\n\ndef parse(x):\n    if isinstance(x, str): return int(x)\n    if isinstance(x, bytes): return int(x.decode())\n    return x", "purpose": "Function with @overload signatures for type checking", "explanation": "@overload tells the type checker what each accepted input shape returns. The actual implementation is the last (un-decorated) definition. mypy + IDEs check call sites against the overloads, so parse('5') and parse(b'5') both type-check to int. Runtime sees only the last definition; @overload signatures are stripped.", "key_concepts": ["typing.overload", "function overloading in Python (compile-time only)"]},
    {"id": "CE-100", "language": "python", "snippet": "import logging.config\n\nLOGGING = {\n    'version': 1,\n    'formatters': {'json': {'format': '%(asctime)s %(levelname)s %(message)s'}},\n    'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'json'}},\n    'loggers': {'myapp': {'handlers': ['console'], 'level': 'INFO'}},\n}\nlogging.config.dictConfig(LOGGING)", "purpose": "Configure Python logging declaratively via dict", "explanation": "dictConfig accepts a structured dict describing formatters, handlers, and loggers. Cleaner than imperative basicConfig + addHandler chains, especially for multi-module apps. Production code typically loads this from YAML / JSON. structlog or python-json-logger replace the formatter for structured (JSON) logs.", "key_concepts": ["logging.config.dictConfig", "declarative log config"]},
    {"id": "CE-101", "language": "go", "snippet": "type Config struct {\n    Host    string `json:\"host\" yaml:\"host\"`\n    Port    int    `json:\"port\" yaml:\"port\" default:\"8080\"`\n    Verbose bool   `json:\"verbose,omitempty\"`\n}", "purpose": "Struct tags drive JSON / YAML serialization", "explanation": "Backtick-string struct tags are key:value metadata read at runtime via reflect. encoding/json uses the json tag for field naming; gopkg.in/yaml.v3 uses yaml. omitempty skips zero-value fields. Same field can have multiple tags for multiple encodings. Custom tags drive other libs (validators, ORM mappings).", "key_concepts": ["struct tags", "encoding/json", "reflection-driven serialization"]},
    {"id": "CE-102", "language": "python", "snippet": "from contextvars import ContextVar\n\nrequest_id: ContextVar[str] = ContextVar('request_id', default='-')\n\nasync def handler():\n    request_id.set('abc-123')\n    log.info(f'in {request_id.get()}')\n    await deeper()\n\nasync def deeper():\n    log.info(f'deeper still: {request_id.get()}')", "purpose": "Context-local variable for async request tracing", "explanation": "ContextVar gives async-safe scoped state. asyncio copies the context per task, so concurrent requests don't see each other's request_id. Use cases: per-request logging context, tracing IDs, user-id-in-current-request. The thread-local equivalent (threading.local) doesn't work for asyncio because tasks share threads.", "key_concepts": ["ContextVar", "async-local state", "request tracing"]},
    {"id": "CE-103", "language": "rust", "snippet": "fn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}", "purpose": "Lifetime annotations on a function returning a reference", "explanation": "'a is a lifetime parameter that ties the returned reference's lifetime to the SHORTER of the two inputs. Without 'a, the compiler can't tell which input the return references and rejects the function. Most lifetimes are elided automatically; you write explicit ones when there's ambiguity (multiple input refs, or returning a ref derived from one of them).", "key_concepts": ["lifetimes", "reference borrowing", "lifetime elision rules"]},
    {"id": "CE-104", "language": "python", "snippet": "from itertools import chain, combinations\n\ndef powerset(iterable):\n    s = list(iterable)\n    return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))\n\nlist(powerset([1, 2, 3]))\n# [(), (1,), (2,), (3,), (1, 2), (1, 3), (2, 3), (1, 2, 3)]", "purpose": "Generate the power set of an iterable", "explanation": "combinations(s, r) yields all r-element subsets. Chaining over r in 0..n gives every possible subset. chain.from_iterable flattens the nested tuples-of-tuples into a single stream. From the official itertools recipes section. For very large sets the power set is 2^n elements, so this only works for small n.", "key_concepts": ["combinations", "chain.from_iterable", "power set construction"]},
    {"id": "CE-105", "language": "python", "snippet": "from inspect import signature\n\ndef wrap(fn):\n    sig = signature(fn)\n    def wrapper(*args, **kwargs):\n        bound = sig.bind(*args, **kwargs)\n        bound.apply_defaults()\n        print(f'calling {fn.__name__} with {bound.arguments}')\n        return fn(*args, **kwargs)\n    return wrapper", "purpose": "Decorator that logs all argument names + values via inspect", "explanation": "inspect.signature returns the function's parameter list. sig.bind validates and binds the args/kwargs to the parameter names. apply_defaults fills in any missing parameters with their defaults. bound.arguments is an OrderedDict of {name: value}. Useful for typed logging, schema generation, replay debuggers.", "key_concepts": ["inspect.signature", "BoundArguments", "introspection"]},
    {"id": "CE-106", "language": "python", "snippet": "import sqlite3\n\nclass Repo:\n    def __init__(self, db: str):\n        self.conn = sqlite3.connect(db)\n        self.conn.row_factory = sqlite3.Row\n\n    def get_user(self, uid: int) -> dict:\n        cur = self.conn.execute(\n            'SELECT id, name, email FROM users WHERE id = ?', (uid,)\n        )\n        row = cur.fetchone()\n        return dict(row) if row else None", "purpose": "Repository pattern wrapping SQLite with typed dict returns", "explanation": "row_factory = sqlite3.Row makes columns accessible by name (row['name']) and lets dict(row) work. The Repo class encapsulates DB access — callers don't touch the connection directly, so swapping SQLite for Postgres later is one class to change. dict-of-rows is friendlier than tuples for downstream JSON serialization.", "key_concepts": ["repository pattern", "sqlite3.Row factory", "encapsulating I/O"]},
    {"id": "CE-107", "language": "python", "snippet": "import contextlib\n\n@contextlib.contextmanager\ndef advisory_lock(conn, key: int):\n    conn.execute('SELECT pg_advisory_lock(%s)', (key,))\n    try:\n        yield\n    finally:\n        conn.execute('SELECT pg_advisory_unlock(%s)', (key,))", "purpose": "PostgreSQL advisory lock as a context manager", "explanation": "PostgreSQL advisory locks are application-defined locks (not row/table locks) keyed by an integer. Useful for cross-process leader election, idempotent migration scripts, single-instance jobs. The CM acquires on entry and always releases on exit. For session-scope locks they release at session close; for transaction-scope use pg_advisory_xact_lock.", "key_concepts": ["advisory locks", "PostgreSQL pg_advisory_lock", "leader election"]},
    {"id": "CE-108", "language": "python", "snippet": "import time\nfrom collections import deque\n\nclass RateLimiter:\n    def __init__(self, max_calls: int, period: float):\n        self.max_calls = max_calls\n        self.period = period\n        self.calls = deque()\n    def allow(self) -> bool:\n        now = time.monotonic()\n        while self.calls and self.calls[0] < now - self.period:\n            self.calls.popleft()\n        if len(self.calls) < self.max_calls:\n            self.calls.append(now)\n            return True\n        return False", "purpose": "Sliding-window rate limiter", "explanation": "Tracks call timestamps in a deque. On each query, evict timestamps older than the window. If under the limit, record and return True. time.monotonic is robust against system clock changes. For distributed rate limiting use Redis with a sorted set; for per-process this in-memory version is fine.", "key_concepts": ["sliding window", "rate limiting", "monotonic clock"]},
    {"id": "CE-109", "language": "go", "snippet": "package main\n\nimport (\n    \"context\"\n    \"errors\"\n    \"fmt\"\n    \"golang.org/x/sync/errgroup\"\n)\n\nfunc fetchAll(ctx context.Context, urls []string) error {\n    g, ctx := errgroup.WithContext(ctx)\n    for _, u := range urls {\n        u := u\n        g.Go(func() error {\n            return fetch(ctx, u)\n        })\n    }\n    return g.Wait()\n}", "purpose": "Concurrent fetches with errgroup for cancel-on-first-error", "explanation": "errgroup.WithContext returns a Group + a derived context. g.Go runs each func concurrently. If ANY returns an error (or panics), the group cancels the derived context and Wait returns that error. Cleanly cancels in-flight requests on first failure. The `u := u` shadow is the pre-Go-1.22 fix for the loop-variable-capture problem.", "key_concepts": ["errgroup", "cancel on first error", "loop variable capture"]},
    {"id": "CE-110", "language": "python", "snippet": "from typing import NamedTuple\n\nclass Point(NamedTuple):\n    x: float\n    y: float\n    label: str = ''\n\np = Point(1.0, 2.0, label='origin')\nprint(p.x, p.label)\nx, y, _ = p  # tuple unpack still works", "purpose": "NamedTuple for immutable, tuple-compatible value types", "explanation": "NamedTuple gives you the ergonomics of a class (named field access, defaults) plus tuple compatibility (unpacking, indexing, immutability). Lighter than @dataclass(frozen=True): no per-instance __dict__, smaller memory. Choose dataclass for richer behaviour (custom __init__, mutability, inheritance) and NamedTuple for plain immutable records.", "key_concepts": ["NamedTuple", "immutable record types", "tuple compatibility"]},
    {"id": "CE-111", "language": "python", "snippet": "import os, signal\n\ndef set_signal_handler():\n    def handler(signum, frame):\n        print(f'caught {signum}, shutting down')\n        # cleanup before exit\n        os._exit(0)\n    signal.signal(signal.SIGTERM, handler)\n    signal.signal(signal.SIGINT, handler)", "purpose": "Graceful shutdown on SIGTERM / SIGINT", "explanation": "signal.signal registers a handler called when the process receives the signal. SIGTERM is what kubectl, systemd, docker stop send. SIGINT is Ctrl-C. The handler should be quick (signal handlers run in interrupted context). os._exit(0) bypasses Python's at-exit hooks; for cleaner shutdown raise SystemExit which lets finally blocks run.", "key_concepts": ["signal handlers", "SIGTERM / SIGINT", "graceful shutdown"]},
    {"id": "CE-112", "language": "javascript", "snippet": "class TaskRunner {\n  #tasks = [];\n  add(task) { this.#tasks.push(task); }\n  async run() {\n    return Promise.all(this.#tasks.map(t => t()));\n  }\n}", "purpose": "Class with private fields (# prefix) running async tasks in parallel", "explanation": "ES2022 class fields with # prefix are truly private — no name mangling, can't be accessed from outside even via reflection. Promise.all waits for all promises to resolve (or any to reject). Returns an array in the same order as input. For first-success-wins use Promise.race; for resilient parallelism use Promise.allSettled.", "key_concepts": ["private class fields", "Promise.all", "parallel async"]},
    {"id": "CE-113", "language": "python", "snippet": "import json\nimport gzip\nfrom pathlib import Path\n\ndef append_jsonl_gz(path: Path, record: dict) -> None:\n    line = json.dumps(record, ensure_ascii=False) + '\\n'\n    with gzip.open(path, 'at', encoding='utf-8') as f:\n        f.write(line)", "purpose": "Append a JSON line to a gzip-compressed JSONL file", "explanation": "JSONL (JSON Lines) is one JSON object per line — streaming-friendly, append-friendly. gzip.open in 'at' mode appends compressed; each call writes a small gzip member, so the file is technically a multi-stream gzip (still readable normally by gzip / zcat). Common for log shipping, analytics events, ML training data.", "key_concepts": ["JSONL format", "gzip append mode", "streaming append"]},
    {"id": "CE-114", "language": "python", "snippet": "import asyncio, signal\n\nasync def main():\n    stop = asyncio.Event()\n    loop = asyncio.get_running_loop()\n    for sig in (signal.SIGINT, signal.SIGTERM):\n        loop.add_signal_handler(sig, stop.set)\n    print('serving until SIGINT or SIGTERM')\n    await stop.wait()\n    print('shutting down cleanly')\n\nasyncio.run(main())", "purpose": "Async server with cooperative shutdown on signal", "explanation": "asyncio.Event is the async-safe analog of threading.Event. The signal handlers set the event without blocking the event loop. main() awaits the event, performing whatever cleanup is needed before returning. Beats the synchronous signal.signal approach because the rest of asyncio keeps running normally up to the wait.", "key_concepts": ["asyncio.Event", "loop.add_signal_handler", "cooperative shutdown"]},
    {"id": "CE-115", "language": "rust", "snippet": "use std::sync::OnceLock;\n\nstatic CONFIG: OnceLock<Config> = OnceLock::new();\n\nfn get_config() -> &'static Config {\n    CONFIG.get_or_init(|| load_config())\n}", "purpose": "Lazy-initialised global with std::sync::OnceLock", "explanation": "OnceLock guarantees the closure runs at most once even under concurrent access. Returns &T after init. For one-time init use OnceLock; for per-thread lazy init use thread_local!. Pre-1.70 the lazy_static / once_cell crates gave the same. The standard library now provides this without external deps.", "key_concepts": ["OnceLock", "lazy global init", "thread-safe single init"]},
    {"id": "CE-116", "language": "python", "snippet": "import sqlite3\n\nschema = '''\nCREATE TABLE IF NOT EXISTS migrations(version INTEGER PRIMARY KEY);\nINSERT OR IGNORE INTO migrations VALUES(0);\n'''\n\ndef migrate(conn):\n    conn.executescript(schema)\n    cur = conn.execute('SELECT version FROM migrations LIMIT 1')\n    current = cur.fetchone()[0]\n    if current < 1:\n        conn.execute('CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT)')\n        conn.execute('UPDATE migrations SET version = 1')\n        conn.commit()", "purpose": "Tiny hand-rolled migration system", "explanation": "Tracks current schema version in a single-row table. Each version's migration runs only if not yet applied. Atomic: wraps changes + version bump in a transaction. For real applications use Alembic (Python), Goose (Go), Flyway (JVM) etc; this pattern is the educational core they all build on.", "key_concepts": ["schema migrations", "version table", "idempotent CREATE IF NOT EXISTS"]},
    {"id": "CE-117", "language": "python", "snippet": "from typing import TypedDict\n\nclass User(TypedDict):\n    id: int\n    name: str\n    email: str\n\ndef greet(u: User) -> str:\n    return f'Hello, {u[\"name\"]}'", "purpose": "Typed dictionaries with structural typing", "explanation": "TypedDict declares the keys + types of a dict; mypy checks that callers pass the right shape. Cleaner than dataclass for JSON-shaped data because it reads/writes as a regular dict (json.loads output, FastAPI body parsing, Pydantic v2 .model_dump output). Doesn't validate at runtime — it's a type-checker construct only.", "key_concepts": ["TypedDict", "structural typing on dicts", "mypy verification"]},
    {"id": "CE-118", "language": "javascript", "snippet": "const obj = { name: 'Alice', age: 30, email: 'a@b.c' };\nconst { name, ...rest } = obj;\n// name = 'Alice', rest = { age: 30, email: 'a@b.c' }\nconst merged = { ...rest, age: 31 };", "purpose": "Object rest / spread for destructuring and shallow merge", "explanation": "Rest in destructuring `...rest` collects remaining properties into a new object. Spread in object literal `...rest` copies properties into the new object. The order of spreads matters: later keys override earlier ones. Shallow only — nested objects are shared by reference. The array equivalents [...arr] / [first, ...rest] work the same way.", "key_concepts": ["object spread", "rest destructuring", "shallow merge"]},
    {"id": "CE-119", "language": "python", "snippet": "from dataclasses import dataclass, field\nfrom typing import ClassVar\n\n@dataclass\nclass Config:\n    DEFAULT_PORT: ClassVar[int] = 8080  # not an instance field\n    host: str = 'localhost'\n    port: int = DEFAULT_PORT", "purpose": "ClassVar to mark a class-level (non-instance) attribute on a dataclass", "explanation": "Without ClassVar, dataclass would treat DEFAULT_PORT as an instance field with a default value. ClassVar tells dataclass to skip it — the attribute lives only on the class, not on instances. Useful for constants, registries, or shared state attached to the class itself.", "key_concepts": ["ClassVar", "dataclass field semantics", "class vs instance attributes"]},
    {"id": "CE-120", "language": "python", "snippet": "import importlib\n\ndef load_plugin(qualname: str):\n    module_name, _, class_name = qualname.rpartition('.')\n    module = importlib.import_module(module_name)\n    return getattr(module, class_name)\n\nPlugin = load_plugin('myapp.plugins.HelloPlugin')", "purpose": "Dynamic plugin loading from a dotted-path string", "explanation": "rpartition('.') splits at the LAST dot, separating module from name. import_module imports the module by name. getattr fetches the class. Pattern shows up in: Django setting CLASSES, Celery tasks, pytest fixtures, anywhere a config file names a class that the framework instantiates dynamically.", "key_concepts": ["importlib", "dynamic import", "plugin pattern"]},
]


# 40 more code-write patterns covering: web framework handlers,
# more DB ops, more concurrency primitives, more hashing, more
# regex / string, more file I/O, math, type validation, async
# patterns, more language-specific.
WRITE_PATTERNS = [
    {"id": "CW-081", "language": "python", "description": "Define a FastAPI POST endpoint that creates a user and returns it", "implementation": "from fastapi import FastAPI\nfrom pydantic import BaseModel\napp = FastAPI()\nclass CreateUser(BaseModel):\n    name: str\n    email: str\n@app.post('/users', status_code=201)\ndef create(user: CreateUser):\n    return {'id': 1, **user.model_dump()}", "explanation": "Pydantic v2 model_dump() returns a dict. status_code=201 (Created) is the right HTTP code for resource creation. FastAPI auto-validates the body against the Pydantic schema and returns 422 on failure with a structured error."},
    {"id": "CW-082", "language": "python", "description": "Define a Flask DELETE endpoint with auth check", "implementation": "from flask import Flask, abort\nfrom myauth import current_user\napp = Flask(__name__)\n@app.delete('/users/<int:user_id>')\ndef delete_user(user_id: int):\n    me = current_user()\n    if me is None: abort(401)\n    if me.id != user_id and not me.is_admin: abort(403)\n    do_delete(user_id)\n    return '', 204", "explanation": "204 No Content is the right code for a successful delete with no body. 401 = not authenticated, 403 = authenticated but not authorised. Always check both ownership and admin override; DELETE without auth is the canonical IDOR / privilege-escalation bug."},
    {"id": "CW-083", "language": "python", "description": "Implement a SQL query with named parameters in psycopg", "implementation": "import psycopg\nwith psycopg.connect(dsn) as conn:\n    with conn.cursor() as cur:\n        cur.execute(\n            'SELECT id, name FROM users WHERE active = %(active)s AND created_after = %(since)s',\n            {'active': True, 'since': '2024-01-01'}\n        )\n        for row in cur:\n            print(row)", "explanation": "Named parameters %(name)s are clearer than positional %s when the query has many params. psycopg auto-escapes. Iterating the cursor streams rows lazily — for very large result sets, fetchmany or server-side cursor (cur.itersize) keeps memory bounded."},
    {"id": "CW-084", "language": "python", "description": "Implement an in-memory rate limiter with sliding window", "implementation": "import time\nfrom collections import deque\nclass RateLimiter:\n    def __init__(self, max_calls: int, period: float):\n        self.max_calls, self.period, self.calls = max_calls, period, deque()\n    def allow(self) -> bool:\n        now = time.monotonic()\n        while self.calls and self.calls[0] < now - self.period:\n            self.calls.popleft()\n        if len(self.calls) < self.max_calls:\n            self.calls.append(now); return True\n        return False", "explanation": "Sliding-window: track call timestamps in a deque, evict expired ones, accept if under cap. time.monotonic resists wall-clock changes. For multi-process or distributed limiting, store the timestamps in Redis (ZSET with scores)."},
    {"id": "CW-085", "language": "python", "description": "Build a JWT signed with HMAC-SHA256", "implementation": "import json, hmac, hashlib, base64, time\ndef sign_jwt(payload: dict, secret: str) -> str:\n    header = {'alg': 'HS256', 'typ': 'JWT'}\n    def b64(d): return base64.urlsafe_b64encode(json.dumps(d).encode()).rstrip(b'=').decode()\n    h, p = b64(header), b64(payload)\n    sig = hmac.new(secret.encode(), f'{h}.{p}'.encode(), hashlib.sha256).digest()\n    s = base64.urlsafe_b64encode(sig).rstrip(b'=').decode()\n    return f'{h}.{p}.{s}'", "explanation": "JWT = base64url(header) . base64url(payload) . base64url(hmac). URL-safe base64 swaps + and /; padding stripped. For real JWT use the PyJWT library; this rolls it for clarity. Never accept algorithm 'none' (CVE-2018-1000531 family); pin alg server-side."},
    {"id": "CW-086", "language": "python", "description": "Verify a JWT signature with constant-time comparison", "implementation": "def verify_jwt(token: str, secret: str) -> dict:\n    h, p, s = token.split('.')\n    expected = hmac.new(secret.encode(), f'{h}.{p}'.encode(), hashlib.sha256).digest()\n    s_padded = s + '=' * (-len(s) % 4)\n    actual = base64.urlsafe_b64decode(s_padded)\n    if not hmac.compare_digest(expected, actual):\n        raise ValueError('bad signature')\n    p_padded = p + '=' * (-len(p) % 4)\n    return json.loads(base64.urlsafe_b64decode(p_padded))", "explanation": "Re-pad base64 with '=' to a multiple of 4 chars before decoding (urlsafe_b64encode strips them). hmac.compare_digest is constant-time; never use == on signatures. Production-grade verification also checks exp, nbf, iss, aud claims."},
    {"id": "CW-087", "language": "python", "description": "Detect file MIME type by sniffing initial bytes", "implementation": "def sniff_mime(blob: bytes) -> str:\n    sigs = [\n        (b'\\x89PNG\\r\\n\\x1a\\n', 'image/png'),\n        (b'\\xff\\xd8\\xff', 'image/jpeg'),\n        (b'GIF8', 'image/gif'),\n        (b'%PDF-', 'application/pdf'),\n        (b'PK\\x03\\x04', 'application/zip'),\n    ]\n    for sig, mime in sigs:\n        if blob.startswith(sig):\n            return mime\n    return 'application/octet-stream'", "explanation": "Trust the bytes, not the filename or client-supplied Content-Type. python-magic wraps libmagic for thousands more formats. Used for safe file uploads — reject if the sniffed type doesn't match the expected set, before serving back to other users."},
    {"id": "CW-088", "language": "python", "description": "Apply gzip compression to a response body", "implementation": "import gzip, io\ndef gzip_compress(data: bytes) -> bytes:\n    buf = io.BytesIO()\n    with gzip.GzipFile(fileobj=buf, mode='wb', mtime=0) as f:\n        f.write(data)\n    return buf.getvalue()", "explanation": "mtime=0 makes the output deterministic — without it the gzip header includes the current time, so bytewise-equal inputs produce different bytes. Useful for caching and content-addressed storage. Set Content-Encoding: gzip header when serving."},
    {"id": "CW-089", "language": "python", "description": "Generate a deterministic hash-based ID for a record", "implementation": "import hashlib\ndef record_id(payload: dict) -> str:\n    canonical = json.dumps(payload, sort_keys=True, separators=(',', ':'))\n    return hashlib.sha256(canonical.encode()).hexdigest()[:16]", "explanation": "json.dumps with sort_keys + separators produces a canonical string regardless of dict order. SHA-256 hex first 16 chars (64 bits) is enough to avoid collisions for any realistic dataset. Used for idempotency keys, cache keys, content-addressed storage."},
    {"id": "CW-090", "language": "python", "description": "Implement a simple feature-flag check from environment", "implementation": "import os\ndef flag_enabled(name: str, default: bool = False) -> bool:\n    val = os.environ.get(f'FEATURE_{name.upper()}')\n    if val is None: return default\n    return val.lower() in ('1', 'true', 'yes', 'on')", "explanation": "Convention-over-configuration: FEATURE_X=1 enables flag X. Multiple truthy strings to handle 'true', '1', 'yes' which different teams use. For production-grade flags use LaunchDarkly, Statsig, or growthbook; this in-process version is fine for env-driven deployment toggles."},
    {"id": "CW-091", "language": "python", "description": "Implement exponential backoff with jitter", "implementation": "import random, time\ndef backoff(attempt: int, base: float = 0.5, cap: float = 30.0) -> float:\n    delay = min(cap, base * (2 ** attempt))\n    return random.uniform(0, delay)\n\nfor attempt in range(5):\n    try: return do_request()\n    except Exception:\n        time.sleep(backoff(attempt))\nraise RuntimeError('out of attempts')", "explanation": "Exponential growth (base * 2^attempt) capped at cap to avoid hour-long delays. random.uniform(0, delay) is the AWS 'full jitter' algorithm — prevents thundering-herd retries where many clients retry in lockstep. Used in every robust HTTP client / DB connection retry."},
    {"id": "CW-092", "language": "python", "description": "Walk a JSON tree replacing string values with redactions for sensitive keys", "implementation": "SENSITIVE = {'password', 'api_key', 'token', 'secret'}\ndef redact(obj):\n    if isinstance(obj, dict):\n        return {k: '<redacted>' if k.lower() in SENSITIVE else redact(v) for k, v in obj.items()}\n    if isinstance(obj, list):\n        return [redact(x) for x in obj]\n    return obj", "explanation": "Recursive walk. Dict comprehension redacts values whose key matches the sensitive set (case-insensitive). For logging request/response bodies, before they hit your log aggregator. Production code expands the sensitive list and pattern-matches partial keys ('credit_card_*')."},
    {"id": "CW-093", "language": "python", "description": "Implement a circular buffer / ring buffer", "implementation": "class RingBuffer:\n    def __init__(self, size: int):\n        self.size = size\n        self.buf = [None] * size\n        self.start = self.count = 0\n    def push(self, x):\n        idx = (self.start + self.count) % self.size\n        self.buf[idx] = x\n        if self.count < self.size:\n            self.count += 1\n        else:\n            self.start = (self.start + 1) % self.size\n    def items(self):\n        for i in range(self.count):\n            yield self.buf[(self.start + i) % self.size]", "explanation": "Fixed-size queue overwriting oldest on overflow. O(1) push, O(1) per-item read. Useful for last-N-events buffers (recent log lines, last-N requests for moving average). collections.deque(maxlen=N) does the same at higher level; this is the textbook implementation."},
    {"id": "CW-094", "language": "python", "description": "Read all environment variables matching a prefix", "implementation": "import os\ndef env_prefix(prefix: str) -> dict:\n    return {\n        k[len(prefix):]: v\n        for k, v in os.environ.items()\n        if k.startswith(prefix)\n    }\n\nconfig = env_prefix('MYAPP_')  # MYAPP_HOST, MYAPP_PORT, ...", "explanation": "Strip the prefix and return as a dict. Common pattern for 12-factor config: app reads MYAPP_DATABASE_URL, MYAPP_REDIS_URL, etc. Combined with type coercion (CW-079) and defaulting, this is the entire config-loading layer."},
    {"id": "CW-095", "language": "python", "description": "Implement a topological sort", "implementation": "from collections import defaultdict, deque\ndef toposort(graph: dict) -> list:\n    in_deg = defaultdict(int)\n    for u in graph:\n        in_deg.setdefault(u, 0)\n        for v in graph[u]:\n            in_deg[v] += 1\n    q = deque([n for n, d in in_deg.items() if d == 0])\n    out = []\n    while q:\n        u = q.popleft(); out.append(u)\n        for v in graph.get(u, []):\n            in_deg[v] -= 1\n            if in_deg[v] == 0:\n                q.append(v)\n    if len(out) != len(in_deg):\n        raise ValueError('cycle')\n    return out", "explanation": "Kahn's algorithm. Compute in-degrees, queue all nodes with in-degree 0, process them in order, decrementing successors. If output length doesn't match node count, a cycle exists (those nodes never reached in-degree 0). Used for build-system task ordering, Python module import order analysis, dependency resolution."},
    {"id": "CW-096", "language": "python", "description": "Recursively flatten a nested list", "implementation": "def flatten(items):\n    for x in items:\n        if isinstance(x, list):\n            yield from flatten(x)\n        else:\n            yield x", "explanation": "Generator with `yield from` recurses into sub-lists, yields each scalar. Lazy: only one item in memory at a time. Doesn't handle tuples or dicts unless extended; for arbitrary iterables substitute isinstance(x, (list, tuple)). For strings, beware: strings are iterable, so add a string-exclusion check if you don't want them recursed into."},
    {"id": "CW-097", "language": "python", "description": "Decorator that times a function and logs duration", "implementation": "import time, functools, logging\nlog = logging.getLogger(__name__)\ndef timed(fn):\n    @functools.wraps(fn)\n    def wrapper(*args, **kwargs):\n        t0 = time.perf_counter()\n        try:\n            return fn(*args, **kwargs)\n        finally:\n            elapsed = time.perf_counter() - t0\n            log.info('%s took %.3fs', fn.__name__, elapsed)\n    return wrapper", "explanation": "perf_counter is the highest-resolution monotonic clock. functools.wraps preserves the wrapped function's name and docstring. try/finally logs even when the function raises. For production tracing, OpenTelemetry's @tracer.start_as_current_span decorator does this plus distributed tracing context."},
    {"id": "CW-098", "language": "python", "description": "Group records into a dict-of-lists keyed by computed key", "implementation": "from collections import defaultdict\ndef group_by(items, keyfn):\n    out = defaultdict(list)\n    for x in items:\n        out[keyfn(x)].append(x)\n    return dict(out)\n\nby_team = group_by(employees, lambda e: e['team'])", "explanation": "Higher-order function that takes a key extractor; clearer than a hand-rolled dict-update loop and reusable across types. itertools.groupby exists but requires sorted input; this version handles unordered iterables. Pandas DataFrame.groupby is the industrial-strength version for tabular data."},
    {"id": "CW-099", "language": "python", "description": "Generate a random password meeting complexity rules", "implementation": "import secrets, string\ndef generate_password(length: int = 16) -> str:\n    chars = string.ascii_letters + string.digits + '!@#$%^&*'\n    while True:\n        pw = ''.join(secrets.choice(chars) for _ in range(length))\n        if (any(c.islower() for c in pw)\n            and any(c.isupper() for c in pw)\n            and any(c.isdigit() for c in pw)\n            and any(c in '!@#$%^&*' for c in pw)):\n            return pw", "explanation": "secrets module is for cryptographic randomness — use it, NOT random, for passwords / tokens / keys. random uses Mersenne Twister which is predictable. The retry loop ensures all four character classes are represented (rejection sampling). For passwordless authentication or passkeys, a 256-bit random value is enough."},
    {"id": "CW-100", "language": "python", "description": "Stream a generator output to stdout as JSON Lines", "implementation": "import json, sys\ndef stream_jsonl(records):\n    for r in records:\n        sys.stdout.write(json.dumps(r, ensure_ascii=False) + '\\n')\n        sys.stdout.flush()", "explanation": "Each record is one JSON object on its own line (JSONL format). flush after each line so consumers (tee | tail | jq) see records in real time, not in OS-page-buffered chunks. Useful for pipeline-friendly CLI tools, log producers, ML data pipelines."},
    {"id": "CW-101", "language": "go", "description": "Define a struct that implements the io.Reader interface", "implementation": "type LimitedReader struct {\n    src io.Reader\n    n   int64\n}\n\nfunc (l *LimitedReader) Read(p []byte) (int, error) {\n    if l.n <= 0 { return 0, io.EOF }\n    if int64(len(p)) > l.n { p = p[:l.n] }\n    nr, err := l.src.Read(p)\n    l.n -= int64(nr)\n    return nr, err\n}", "explanation": "Implements io.Reader by satisfying its single method. Composes onto any io.Reader to limit total bytes read. Standard library has io.LimitReader doing exactly this. Go's interface satisfaction is structural — no `implements` keyword, the method set determines compatibility."},
    {"id": "CW-102", "language": "go", "description": "Implement a generic Map function for a slice", "implementation": "func Map[T, R any](in []T, fn func(T) R) []R {\n    out := make([]R, len(in))\n    for i, x := range in {\n        out[i] = fn(x)\n    }\n    return out\n}\n\ndoubled := Map([]int{1, 2, 3}, func(x int) int { return x * 2 })", "explanation": "Go 1.18+ generics. Two type parameters T (input) and R (output) both constrained to `any`. Pre-allocate the output slice for efficiency. The standard library doesn't include Map / Filter; the official `golang.org/x/exp/slices` and the Go 2 `slices` package have iterators in 1.23+."},
    {"id": "CW-103", "language": "go", "description": "Implement a Result-style return with error wrapping", "implementation": "func parseConfig(path string) (*Config, error) {\n    data, err := os.ReadFile(path)\n    if err != nil {\n        return nil, fmt.Errorf(\"read %s: %w\", path, err)\n    }\n    var c Config\n    if err := json.Unmarshal(data, &c); err != nil {\n        return nil, fmt.Errorf(\"parse %s: %w\", path, err)\n    }\n    return &c, nil\n}", "explanation": "fmt.Errorf with %w wraps the error so errors.Is and errors.As can walk the chain. Each layer adds context (which file). Consumers can call errors.Is(err, fs.ErrNotExist) to check the underlying type, or unwrap to print a structured trace."},
    {"id": "CW-104", "language": "rust", "description": "Define an enum-based result type with helpful error messages", "implementation": "#[derive(Debug, thiserror::Error)]\nenum ConfigError {\n    #[error(\"file not found: {0}\")]\n    NotFound(String),\n    #[error(\"parse error in {file}: {source}\")]\n    Parse {\n        file: String,\n        #[source]\n        source: serde_json::Error,\n    },\n}", "explanation": "thiserror crate generates Display + Error impls from the #[error] attribute. {0} interpolates the first tuple field; named fields use {field}. #[source] marks the underlying error so .source() walks the chain. For the catch-all error type at application boundary, use anyhow::Error instead."},
    {"id": "CW-105", "language": "rust", "description": "Spawn a thread, send a value, return the joined result", "implementation": "use std::thread;\nuse std::sync::mpsc;\nfn main() {\n    let (tx, rx) = mpsc::channel();\n    let handle = thread::spawn(move || {\n        tx.send(42).unwrap();\n    });\n    let value = rx.recv().unwrap();\n    handle.join().unwrap();\n    println!(\"{}\", value);\n}", "explanation": "mpsc = multi-producer, single-consumer channel. tx is moved into the thread so only the spawned thread sends. recv blocks until a value arrives. join waits for the thread to finish. For multi-producer multi-consumer use crossbeam-channel or async channels (tokio::sync::mpsc)."},
    {"id": "CW-106", "language": "javascript", "description": "Implement Promise.all from scratch", "implementation": "function promiseAll(promises) {\n  return new Promise((resolve, reject) => {\n    const results = new Array(promises.length);\n    let remaining = promises.length;\n    if (remaining === 0) return resolve([]);\n    promises.forEach((p, i) => {\n      Promise.resolve(p).then(\n        v => { results[i] = v; if (--remaining === 0) resolve(results); },\n        reject\n      );\n    });\n  });\n}", "explanation": "New Promise with executor that captures resolve/reject. Each input promise (or value, via Promise.resolve) settles independently; we count down a remaining counter and resolve with all results when zero. First rejection short-circuits via the shared reject. Empty input case resolves immediately to []."},
    {"id": "CW-107", "language": "javascript", "description": "Implement a Promise-based delay function", "implementation": "function delay(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}\n\nawait delay(1000);  // pause 1 second", "explanation": "setTimeout fires the callback after ms milliseconds. Wrapping in a Promise makes it await-able. Standard pattern for adding delays in async flows. Combined with retry loops: `for (let i = 0; i < 5; i++) { try { ...; break } catch { await delay(2 ** i * 100); } }`."},
    {"id": "CW-108", "language": "javascript", "description": "Implement a tiny pub/sub event bus", "implementation": "const bus = {\n  handlers: new Map(),\n  on(event, fn) {\n    if (!this.handlers.has(event)) this.handlers.set(event, new Set());\n    this.handlers.get(event).add(fn);\n    return () => this.off(event, fn);\n  },\n  off(event, fn) {\n    this.handlers.get(event)?.delete(fn);\n  },\n  emit(event, ...args) {\n    for (const fn of this.handlers.get(event) ?? []) fn(...args);\n  }\n};", "explanation": "Map of event-name to Set of handlers. Set gives O(1) delete. on returns an unsubscribe function — calling it removes the handler. The optional-chaining `?? []` handles unknown events without throwing. Used for decoupled module communication, UI updates, plugin hooks."},
    {"id": "CW-109", "language": "python", "description": "Write a context manager that times a block of code", "implementation": "from contextlib import contextmanager\nimport time\n\n@contextmanager\ndef timer(label='block'):\n    t0 = time.perf_counter()\n    yield\n    elapsed = time.perf_counter() - t0\n    print(f'{label}: {elapsed:.3f}s')\n\nwith timer('expensive op'):\n    do_work()", "explanation": "contextmanager turns a generator into a context manager. Code before yield runs on __enter__, code after on __exit__. For try/finally semantics (timer prints even on exception), wrap yield in try/finally — the version above does NOT log on exception."},
    {"id": "CW-110", "language": "python", "description": "Write a function that chunks an iterable into fixed-size pieces", "implementation": "from itertools import islice\ndef chunked(it, n):\n    it = iter(it)\n    while chunk := list(islice(it, n)):\n        yield chunk", "explanation": "islice takes the next n items from the iterator (consuming them). The walrus operator `:=` assigns and tests in one step — when islice returns empty (input exhausted), the loop exits. Lazy: only one chunk in memory at a time. Python 3.12 has itertools.batched doing the same in C."},
    {"id": "CW-111", "language": "python", "description": "Find the most common element in an iterable", "implementation": "from collections import Counter\ndef most_common(items, n=1):\n    return Counter(items).most_common(n)\n\ntop_one = most_common(['a','b','a','c','a','b'])\n# [('a', 3)]", "explanation": "Counter.most_common(n) returns the top-n (item, count) pairs. With no argument, returns all items sorted by count descending. statistics.mode in 3.8+ returns the single most common item but raises StatisticsError on ties; multimode returns all tied modes."},
    {"id": "CW-112", "language": "python", "description": "Implement a thread-safe singleton via metaclass", "implementation": "import threading\nclass Singleton(type):\n    _instances = {}\n    _lock = threading.Lock()\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            with cls._lock:\n                if cls not in cls._instances:\n                    cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls._instances[cls]\n\nclass DBPool(metaclass=Singleton):\n    def __init__(self):\n        self.connections = []", "explanation": "Double-checked locking: fast path skips the lock when the instance already exists. The metaclass overrides __call__ (which is invoked when you do MyClass()), so only one instance is ever created. Pythonic alternative: just create a module-level instance at import time. Module imports are atomic in CPython."},
    {"id": "CW-113", "language": "python", "description": "Convert a snake_case string to camelCase", "implementation": "def snake_to_camel(s: str) -> str:\n    parts = s.split('_')\n    return parts[0] + ''.join(p.title() for p in parts[1:])\n\nsnake_to_camel('hello_world_foo')  # 'helloWorldFoo'", "explanation": "Split on underscore, lowercase the first chunk, title-case the rest. Useful for translating between Python snake_case + JavaScript camelCase APIs. PascalCase is similar but you also title-case the first chunk: ''.join(p.title() for p in parts)."},
    {"id": "CW-114", "language": "python", "description": "Build a dataclass that JSON-serializes via __dict__", "implementation": "import json\nfrom dataclasses import dataclass, asdict\n\n@dataclass\nclass User:\n    id: int\n    name: str\n    email: str\n\nu = User(1, 'Alice', 'a@b.c')\nprint(json.dumps(asdict(u)))", "explanation": "asdict from dataclasses converts the dataclass instance to a plain dict, recursing into nested dataclasses. Combined with json.dumps gives you a serialised form. For richer schemas (validation, custom serialisation, ORM integration) Pydantic is the right tool."},
    {"id": "CW-115", "language": "python", "description": "Read a CSV streaming row by row, decoded as DictReader", "implementation": "import csv\ndef stream_csv(path: str):\n    with open(path, newline='') as f:\n        for row in csv.DictReader(f):\n            yield row\n\nfor user in stream_csv('users.csv'):\n    print(user['email'])", "explanation": "newline='' is required for csv to handle quoted multi-line fields correctly across platforms. DictReader treats the first row as headers; each row becomes a dict. Generator form keeps memory bounded. For very large files, pandas read_csv with chunksize= is faster but loads pandas."},
    {"id": "CW-116", "language": "python", "description": "Flatten a nested dict using dot-notation keys", "implementation": "def flatten_dict(d, prefix=''):\n    out = {}\n    for k, v in d.items():\n        key = f'{prefix}.{k}' if prefix else k\n        if isinstance(v, dict):\n            out.update(flatten_dict(v, key))\n        else:\n            out[key] = v\n    return out\n\nflatten_dict({'a': 1, 'b': {'c': 2, 'd': {'e': 3}}})\n# {'a': 1, 'b.c': 2, 'b.d.e': 3}", "explanation": "Recursive walk concatenating dot-separated keys. Useful for converting deeply nested config to flat env-var-style or for indexing into search engines (Elasticsearch). For arrays, extend with index-style keys ('items.0.name'). The reverse (un-flatten) sets nested keys back via repeated dict.setdefault."},
    {"id": "CW-117", "language": "python", "description": "Query parameters from a URL-style query string", "implementation": "from urllib.parse import parse_qsl\ndef parse_query(q: str) -> dict:\n    return dict(parse_qsl(q.lstrip('?'), keep_blank_values=True))\n\nparse_query('?name=Alice&page=2&q=')\n# {'name': 'Alice', 'page': '2', 'q': ''}", "explanation": "parse_qsl returns a list of (key, value) tuples in input order, decoding URL-encoded chars. dict() collapses duplicates (last wins); use parse_qs if duplicates matter. keep_blank_values=True preserves keys with empty values rather than dropping them."},
    {"id": "CW-118", "language": "python", "description": "Write a function that returns the SHA-256 fingerprint of a directory's contents", "implementation": "import hashlib\nfrom pathlib import Path\n\ndef dir_sha256(root: str) -> str:\n    h = hashlib.sha256()\n    for path in sorted(Path(root).rglob('*')):\n        if not path.is_file(): continue\n        rel = path.relative_to(root).as_posix()\n        h.update(rel.encode())\n        h.update(b'\\0')\n        h.update(path.read_bytes())\n        h.update(b'\\0')\n    return h.hexdigest()", "explanation": "Sorted iteration ensures deterministic order. Uses null bytes as separators between path and content, and between entries (so 'a' + 'b' can't be confused with 'ab'). Useful for content-addressed caching, build-output verification, change detection. Stream the file content for huge files."},
    {"id": "CW-119", "language": "python", "description": "Memoize an async function with TTL expiry", "implementation": "import asyncio, time\n\ndef async_ttl_cache(seconds: float):\n    def decorator(fn):\n        cache = {}\n        async def wrapper(*args):\n            now = time.time()\n            if args in cache:\n                value, expires = cache[args]\n                if expires > now: return value\n            value = await fn(*args)\n            cache[args] = (value, now + seconds)\n            return value\n        return wrapper\n    return decorator\n\n@async_ttl_cache(60)\nasync def fetch_user(uid):\n    return await db.get_user(uid)", "explanation": "Wraps an async function in TTL caching. async wrapper awaits the wrapped fn on cache miss. Doesn't deduplicate concurrent calls for the same key — N callers during a cache miss all run fn N times. For dedup use a {key: Future} pattern with asyncio.shield."},
    {"id": "CW-120", "language": "python", "description": "Run an external command and stream its stdout line by line", "implementation": "import subprocess\ndef stream_output(cmd: list[str]):\n    proc = subprocess.Popen(\n        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,\n        text=True, bufsize=1,\n    )\n    try:\n        for line in proc.stdout:\n            yield line.rstrip('\\n')\n    finally:\n        proc.wait()\n        if proc.returncode != 0:\n            raise RuntimeError(f'{cmd} failed: {proc.returncode}')\n\nfor line in stream_output(['ping', '-c', '3', '8.8.8.8']):\n    print(line)", "explanation": "Popen with stdout=PIPE + text=True + bufsize=1 enables line-buffered streaming. Iterating proc.stdout yields lines as the process produces them, not after it exits. Useful for long-running processes (training jobs, builds). Always wait() in a finally and check returncode."},
]


def _append(bank: Path, patterns: list) -> int:
    if not bank.exists():
        print(f"[error] bank not found: {bank}", file=sys.stderr)
        return 0
    existing = set()
    with bank.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line: continue
            try: existing.add(json.loads(line).get("id"))
            except json.JSONDecodeError: pass
    appended = 0
    with bank.open("a", encoding="utf-8") as f:
        for p in patterns:
            if p["id"] in existing: continue
            f.write(json.dumps(p, ensure_ascii=False) + "\n")
            appended += 1
    return appended


def main() -> int:
    ce = _append(EXPLAIN, EXPLAIN_PATTERNS)
    cw = _append(WRITE, WRITE_PATTERNS)
    print(f"  code-explain: appended {ce}")
    print(f"  code-write:   appended {cw}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
