#!/usr/bin/env python3
"""Phase 5: final push to surpass cybersec SFT count (1,940 records)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPLAIN = REPO_ROOT / "data" / "raw" / "code_explain_patterns.jsonl"
WRITE = REPO_ROOT / "data" / "raw" / "code_write_patterns.jsonl"


def CE(id_, lang, snippet, purpose, explanation, concepts):
    return {"id": id_, "language": lang, "snippet": snippet,
            "purpose": purpose, "explanation": explanation,
            "key_concepts": concepts}


def CW(id_, lang, description, implementation, explanation):
    return {"id": id_, "language": lang, "description": description,
            "implementation": implementation, "explanation": explanation}


EXPLAIN_PATTERNS = [
    CE("CE-161", "python", "from collections import deque\n\nq = deque(maxlen=5)\nfor i in range(10): q.append(i)\nlist(q)  # [5, 6, 7, 8, 9]", "Bounded deque drops oldest entries on overflow", "maxlen makes deque a fixed-size ring buffer in one parameter. Append past the cap auto-drops the oldest. Used for last-N event windows, moving averages.", ["deque", "maxlen", "ring buffer"]),
    CE("CE-162", "python", "from itertools import accumulate, operator\nlist(accumulate([1, 2, 3, 4, 5]))  # [1, 3, 6, 10, 15]\nlist(accumulate([1, 2, 3, 4, 5], operator.mul))  # [1, 2, 6, 24, 120]", "itertools.accumulate yields running totals", "Default is sum; pass any binary function for other accumulations. Lazy generator. Useful for prefix sums, running max/min, factorial sequences.", ["itertools.accumulate", "running totals", "prefix operations"]),
    CE("CE-163", "python", "from typing import Final\n\nMAX_RETRIES: Final = 3\nMAX_RETRIES = 5  # mypy error", "typing.Final marks constants the type checker enforces", "Final tells mypy this name should never be reassigned. Runtime sees a normal variable. Useful for module-level constants, class-level invariants. Different from frozen dataclasses (which freeze instances) — Final freezes the binding.", ["Final", "constants", "type-checker enforcement"]),
    CE("CE-164", "python", "import bisect\nx = [1, 4, 4, 4, 7, 10]\nbisect.bisect_left(x, 4)   # 1\nbisect.bisect_right(x, 4)  # 4", "bisect for binary search insertion points", "bisect_left returns the leftmost position to insert x while keeping the list sorted; bisect_right returns the rightmost. The difference (right - left) gives the count of x. Used for sorted-list maintenance, range counting, percentile lookup.", ["bisect", "binary search", "insertion point"]),
    CE("CE-165", "python", "import shelve\nwith shelve.open('mydata.db') as db:\n    db['users'] = {'alice': {'id': 1}}\n    db['count'] = 42", "shelve provides a persistent dict-like store", "Pickles values to disk, keyed by string. Useful for simple persistent caches, small KV stores. Caveats: not thread-safe, format depends on the underlying dbm module. For production use sqlite, dbm, or a real KV store.", ["shelve", "pickle persistence", "dbm"]),
    CE("CE-166", "python", "import argparse\np = argparse.ArgumentParser()\nsub = p.add_subparsers(dest='cmd')\nbuild = sub.add_parser('build')\nbuild.add_argument('--target')\ndeploy = sub.add_parser('deploy')\nargs = p.parse_args()", "argparse subcommands for git-style CLIs", "add_subparsers groups related commands under the parent. Each subparser has its own arguments. dest='cmd' captures which subcommand was used. Used by git, kubectl, docker, terraform — the convention for multi-action CLIs.", ["argparse subparsers", "subcommand CLI", "dest attribute"]),
    CE("CE-167", "python", "from concurrent.futures import wait, FIRST_COMPLETED\n\nfutures = [ex.submit(slow, x) for x in inputs]\ndone, pending = wait(futures, return_when=FIRST_COMPLETED)", "wait with FIRST_COMPLETED returns as soon as any future finishes", "as_completed iterates all; wait with FIRST_COMPLETED stops on the first. Useful for racing alternative implementations, taking whichever responds first. Also FIRST_EXCEPTION (stop on first error) and ALL_COMPLETED (default).", ["wait", "FIRST_COMPLETED", "racing futures"]),
    CE("CE-168", "python", "from textwrap import dedent\nmsg = dedent('''\\\n    line 1\n    line 2\n''')", "textwrap.dedent strips common leading whitespace from a multi-line string", "Useful for embedding indented strings inline (HTML, SQL, error messages) without leading whitespace artifacts. The leading backslash-newline avoids a leading blank line. inspect.cleandoc does similar but for docstrings.", ["dedent", "multi-line strings"]),
    CE("CE-169", "python", "import functools\n@functools.singledispatch\ndef stringify(x):\n    return str(x)\n@stringify.register\ndef _(x: list):\n    return ','.join(str(y) for y in x)", "functools.singledispatch for type-based polymorphism", "First arg's type drives the dispatch. Cleaner than isinstance chains; easy to extend with new types from outside (third parties can register handlers for the function). Doubles as a poor-man's visitor pattern when classes are open.", ["singledispatch", "type-based dispatch", "open extensibility"]),
    CE("CE-170", "python", "from io import StringIO\nbuf = StringIO()\nbuf.write('hello\\n'); buf.write('world\\n')\nprint(buf.getvalue())", "StringIO is an in-memory file-like object for strings", "Write/read text without touching disk. Useful for: building a file in memory before flushing once, capturing stdout in tests (sys.stdout = StringIO()), wrapping bytes interfaces around strings. BytesIO is the byte equivalent.", ["StringIO", "in-memory file", "io module"]),
    CE("CE-171", "go", "type Option func(*Server)\nfunc WithTimeout(d time.Duration) Option {\n    return func(s *Server) { s.timeout = d }\n}\nfunc NewServer(opts ...Option) *Server {\n    s := &Server{timeout: 5*time.Second}\n    for _, o := range opts { o(s) }\n    return s\n}", "Functional options pattern for configurable Go constructors", "Each option is a function that mutates the constructed value. Add new options without breaking the API. Cleaner than long parameter lists. Used in net/http server configuration, gRPC, many Go libraries.", ["functional options", "variadic configuration"]),
    CE("CE-172", "go", "for i := range items {\n    items[i] = process(items[i])\n}", "Index range loop for in-place modification", "for range gives both index and value; with one variable you get the index. Modifying via index works in-place. for _, v := range items would copy values, so v changes don't propagate. Common gotcha for newcomers.", ["range loop", "in-place modify"]),
    CE("CE-173", "rust", "let mut counts: HashMap<&str, i32> = HashMap::new();\nfor word in text.split_whitespace() {\n    *counts.entry(word).or_insert(0) += 1;\n}", "HashMap entry API for insert-or-update", "entry returns OccupiedEntry or VacantEntry. or_insert(default) returns &mut V whether present or not. Then *... += 1 modifies in place. Cleaner than checking contains_key + insert. or_insert_with(closure) for lazy default.", ["entry API", "insert-or-update", "HashMap"]),
    CE("CE-174", "rust", "let v: Vec<i32> = vec![1, 2, 3];\nlet doubled: Vec<i32> = v.iter().map(|x| x * 2).collect();", "Iterator chain with map and collect", "iter() gives &i32 references; map closure works on the references. collect() drives the chain to completion, accumulating into the type given by annotation. Iterator chains in Rust are zero-cost — compile to the same loops you'd write by hand.", ["iterator chain", "collect", "zero-cost abstraction"]),
    CE("CE-175", "javascript", "const arr = Array.from({length: 5}, (_, i) => i * i);\n// [0, 1, 4, 9, 16]", "Array.from with a length-spec and mapper builds an array of N values", "Array.from accepts iterables OR array-like objects ({length: N}). The second arg is a mapper called with (item, index). Convenient for `range`-like sequences without a Python-style range. Other ways: Array(N).fill().map(...), but that's wordier.", ["Array.from", "array-like length", "synthetic ranges"]),
    CE("CE-176", "javascript", "const cache = new WeakMap();\nfunction expensive(obj) {\n  if (cache.has(obj)) return cache.get(obj);\n  const result = compute(obj);\n  cache.set(obj, result);\n  return result;\n}", "WeakMap for memoization keyed by object identity", "WeakMap keys are weakly held — GC can collect them when no other refs exist. Prevents memory leaks for object-keyed caches. Map would keep keys alive forever. Useful for per-object metadata, computed properties, framework-internal state.", ["WeakMap", "weak references", "memoization"]),
    CE("CE-177", "python", "import importlib.metadata as md\nver = md.version('requests')", "importlib.metadata reads installed package metadata", "Standard library since 3.8 (was importlib_metadata backport before). Read version, entry points, requires lists from any installed package. Replaces pkg_resources from setuptools (deprecated, slow). entry_points enables plugin discovery.", ["importlib.metadata", "package version", "entry points"]),
    CE("CE-178", "python", "import math\nmath.gcd(12, 8)         # 4\nmath.lcm(12, 8)         # 24\nmath.isqrt(25)          # 5 (exact integer sqrt)\nmath.comb(5, 2)         # 10 (binomial coefficient)", "math module integer functions", "gcd/lcm extend to multiple args (3.9+). isqrt avoids float imprecision in sqrt(n) for large ints. comb and perm are binomial / permutation counts. math.factorial, math.prod also available.", ["math integer functions", "isqrt", "binomial coefficients"]),
    CE("CE-179", "python", "import csv\nwith open('out.csv', 'w', newline='') as f:\n    w = csv.writer(f, quoting=csv.QUOTE_NONNUMERIC)\n    w.writerow(['name', 'age'])\n    w.writerows([['Alice', 30], ['Bob', 25]])", "csv.writer with QUOTE_NONNUMERIC", "QUOTE_NONNUMERIC quotes everything except numbers — useful for CSVs consumed by Excel or strict parsers. newline='' is required on Windows so csv handles its own line endings. csv.DictWriter accepts dicts and uses fieldnames as the header.", ["csv writer", "quoting modes", "csv.DictWriter"]),
    CE("CE-180", "python", "from typing import Annotated\nfrom pydantic import Field\n\nclass User(BaseModel):\n    age: Annotated[int, Field(ge=0, le=150)]\n    email: Annotated[str, Field(pattern=r'^[^@]+@[^@]+$')]", "Annotated types for runtime validation metadata", "Annotated[T, ...] attaches metadata to a type. Pydantic Field(...) adds validation rules (ge=0 = >= 0, le=150 = <= 150, pattern=regex). Type checker sees just T; runtime libraries inspect the metadata. Used in FastAPI for request validation, Pydantic, attrs, msgspec.", ["Annotated", "Field validation", "metadata-driven types"]),
    CE("CE-181", "python", "from datetime import datetime, timezone\nnow = datetime.now(timezone.utc)\nprint(now.isoformat())", "Always use timezone-aware datetimes", "datetime.now() with no arg returns naive datetime — easy to mix with aware datetimes and silently produce wrong results. timezone.utc is the standard. Python 3.11+ has datetime.UTC as a shortcut. For other zones use ZoneInfo: from zoneinfo import ZoneInfo.", ["timezone-aware datetime", "datetime.now(tz)", "naive vs aware"]),
    CE("CE-182", "python", "import struct\nblob = struct.pack('>If', 42, 3.14)  # big-endian uint32 + float32\nval, f = struct.unpack('>If', blob)", "struct module packs/unpacks binary formats", "Format strings: '>' big-endian, '<' little-endian; I = uint32, f = float32, q = int64, s = bytes. Used for parsing binary protocols, file formats, network packets without external deps. struct.calcsize('>If') tells you the byte size.", ["struct.pack/unpack", "binary format strings", "endianness"]),
    CE("CE-183", "python", "import socket\nwith socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:\n    s.connect(('example.com', 80))\n    s.sendall(b'GET / HTTP/1.0\\r\\n\\r\\n')\n    print(s.recv(4096))", "Raw TCP socket: connect, send, receive", "AF_INET = IPv4, SOCK_STREAM = TCP. sendall loops until all bytes are written. recv blocks for incoming bytes (returns empty bytes on EOF). For HTTPS use ssl.wrap_socket. For richer protocols use the http.client module or requests.", ["socket", "TCP", "sendall vs send"]),
    CE("CE-184", "python", "import subprocess\nresult = subprocess.run(['git', 'rev-parse', 'HEAD'],\n    capture_output=True, text=True, check=True)\nsha = result.stdout.strip()", "Capture subprocess output as text with check=True", "argv as list (not string) avoids shell injection. capture_output=True captures both stdout + stderr. text=True decodes UTF-8 by default. check=True raises CalledProcessError on non-zero exit. For long-running streaming output use Popen + iterate stdout.", ["subprocess.run", "capture_output", "check=True"]),
    CE("CE-185", "python", "from collections.abc import Iterable\n\ndef flatten(items: Iterable):\n    for x in items:\n        if isinstance(x, Iterable) and not isinstance(x, (str, bytes)):\n            yield from flatten(x)\n        else:\n            yield x", "Recursive flatten that doesn't iterate strings", "Strings are iterable but you usually don't want them flattened to characters. The exclusion check is essential. Iterable from collections.abc covers list, tuple, set, generators, dict_keys etc.", ["recursive generator", "Iterable abc", "string exclusion"]),
    CE("CE-186", "javascript", "const map = new Map([['a', 1], ['b', 2]]);\nmap.size                       // 2\nfor (const [k, v] of map) {}    // iterate entries\nObject.fromEntries(map)         // back to plain object", "Map vs object: ordered, sized, iterable", "Map preserves insertion order, has .size, has .has/.get/.set methods. Object loses non-string keys + has prototype-key conflicts (constructor, __proto__). Use Map for any-keyed dictionary, Object for fixed-shape records.", ["Map", "Object.fromEntries", "Map vs Object"]),
    CE("CE-187", "rust", "fn main() {\n    let s = String::from(\"hello\");\n    let t = &s;       // immutable borrow\n    let u = &s;       // multiple immutable borrows ok\n    println!(\"{} {} {}\", s, t, u);\n}", "Multiple immutable references coexist", "The borrow checker allows any number of & references OR exactly one &mut, never both. After the println these references end (NLL: non-lexical lifetimes), and you could take a &mut afterward. This is the heart of Rust's data-race-free guarantee.", ["borrow checker", "shared references", "NLL"]),
    CE("CE-188", "rust", "fn split_first<T>(v: &mut Vec<T>) -> Option<T> {\n    if v.is_empty() { None } else { Some(v.remove(0)) }\n}", "Owning extraction from a Vec via Option", "v.remove(0) shifts all subsequent elements down (O(n)). Returns owned T (taken out of the Vec). For O(1) remove from front, use VecDeque. Returning Option is idiomatic for fallible operations on collections.", ["Vec::remove", "Option for fallible ops", "owned vs borrowed"]),
    CE("CE-189", "go", "errs := errors.Join(err1, err2, err3)\nif errs != nil {\n    fmt.Println(errs)  // multi-line wrapped errors\n}", "errors.Join (Go 1.20+) wraps multiple errors", "Returns nil if all inputs are nil; otherwise an error whose Error() string is each non-nil error joined with newlines. errors.Is and errors.As walk the joined chain. Useful for cleanup code that may have multiple failures (close 5 files, return all errors).", ["errors.Join", "error aggregation", "Go 1.20"]),
    CE("CE-190", "python", "import zipfile\nwith zipfile.ZipFile('archive.zip') as z:\n    for name in z.namelist():\n        with z.open(name) as f:\n            content = f.read()", "Read files from a zip archive", "ZipFile is a context manager. namelist gives the entries; open returns a file-like object for streaming reads. For writing: ZipFile('out.zip', 'w', zipfile.ZIP_DEFLATED). Beware zip-bomb attacks: bound max extraction size for untrusted inputs.", ["zipfile", "namelist", "zip bomb caveat"]),
    CE("CE-191", "python", "import time\nstart = time.perf_counter()\ndo_work()\nelapsed = time.perf_counter() - start", "perf_counter for high-precision timing", "perf_counter is a monotonic clock with the highest available resolution (sub-microsecond on Linux). Resists wall-clock changes. Use for timing intervals only — its absolute value is meaningless. Wall-clock for timestamps: time.time() or datetime.now().", ["perf_counter", "monotonic clock", "interval timing"]),
    CE("CE-192", "python", "from typing import overload\n@overload\ndef f(x: int) -> int: ...\n@overload\ndef f(x: str) -> str: ...\ndef f(x):\n    return x", "@overload for typed alternative call signatures", "Type checker uses the @overload signatures; runtime sees only the last definition. Useful for functions whose return type depends on the input type. Mypy validates each call site against the overloads; the implementation just needs to handle all cases.", ["typing.overload", "overload signatures"]),
    CE("CE-193", "python", "import secrets\ntoken = secrets.token_urlsafe(32)\n# 'rB7QwGo9...': 256 random bits as URL-safe base64", "secrets module for cryptographically random tokens", "secrets uses os.urandom under the hood — proper CSPRNG. token_urlsafe(N) returns ~ceil(N*4/3) chars of randomness. token_hex(N) returns 2N hex chars. NEVER use random.* for tokens / keys / passwords; use secrets.", ["secrets module", "CSPRNG", "URL-safe tokens"]),
    CE("CE-194", "python", "import unicodedata\nunicodedata.normalize('NFKC', 'café')\nunicodedata.category('A')  # 'Lu' (uppercase letter)", "unicodedata for normalisation and categorisation", "NFC/NFD/NFKC/NFKD: canonical and compatibility normalisation. Different sources can encode the same visual text differently (precomposed é vs e + combining accent); normalising before comparing prevents false negatives. category gives general category classes useful for whitespace / punctuation detection.", ["unicodedata", "normalisation", "Unicode categories"]),
    CE("CE-195", "python", "import warnings\nwarnings.warn('deprecated, use new_func()', DeprecationWarning, stacklevel=2)", "Issue a deprecation warning to callers", "stacklevel=2 makes the warning point at the CALLER's line, not your function's. DeprecationWarning is silenced by default for most users; PendingDeprecationWarning is even quieter; UserWarning is shown by default. python -W default :: forces all warnings on.", ["warnings.warn", "stacklevel", "DeprecationWarning"]),
]


WRITE_PATTERNS = [
    CW("CW-161", "python", "Implement a fixed-size ring buffer with deque", "from collections import deque\nclass RingBuffer:\n    def __init__(self, size): self.buf = deque(maxlen=size)\n    def push(self, x): self.buf.append(x)\n    def items(self): return list(self.buf)", "deque(maxlen=N) auto-drops the oldest on overflow. O(1) push, O(n) for items snapshot. For event windows, moving averages, last-N logs."),
    CW("CW-162", "python", "Compute running totals using itertools.accumulate", "from itertools import accumulate\nlist(accumulate([1, 2, 3, 4]))  # [1, 3, 6, 10]", "Default accumulator is +; pass operator.mul / max / etc. for other ops. Lazy generator; wrap in list() for materialisation."),
    CW("CW-163", "python", "Find an element's insertion point in a sorted list", "import bisect\ndef insertion_point(sorted_list, x):\n    return bisect.bisect_left(sorted_list, x)", "bisect_left for stable insertion before equals; bisect_right for after. Both O(log n). insort to insert in place."),
    CW("CW-164", "python", "Generate cryptographically random URL-safe tokens", "import secrets\ndef new_token(bits=256):\n    return secrets.token_urlsafe(bits // 8)", "secrets uses CSPRNG (os.urandom). Returns base64url-encoded string. NEVER use random.* for security tokens."),
    CW("CW-165", "python", "Build an argparse CLI with subcommands", "import argparse\np = argparse.ArgumentParser()\nsub = p.add_subparsers(dest='cmd')\nbuild = sub.add_parser('build')\nbuild.add_argument('--target')\nargs = p.parse_args()\nif args.cmd == 'build':\n    do_build(args.target)", "subparsers gives git-style nested CLIs. dest captures which subcommand was used. Each subparser has its own arg list."),
    CW("CW-166", "python", "Race multiple workers, return the first result", "from concurrent.futures import wait, FIRST_COMPLETED, ThreadPoolExecutor\nwith ThreadPoolExecutor() as ex:\n    futures = [ex.submit(slow, x) for x in inputs]\n    done, pending = wait(futures, return_when=FIRST_COMPLETED)\n    return next(iter(done)).result()", "wait with FIRST_COMPLETED returns as soon as any future finishes. Useful for racing fallbacks or hedged requests."),
    CW("CW-167", "python", "Use textwrap.dedent for inline indented strings", "from textwrap import dedent\nmsg = dedent('''\\\n    Hello, World\n    Multi-line\n''')", "Strips common leading whitespace. The leading '\\' avoids a blank first line. Useful for SQL strings, error messages, embedded HTML."),
    CW("CW-168", "python", "Define a singledispatch generic function", "from functools import singledispatch\n@singledispatch\ndef stringify(x): return str(x)\n@stringify.register\ndef _(x: list): return ','.join(map(str, x))", "First-arg type drives the dispatch. Cleaner than isinstance chains. Open extensibility — register more types from anywhere."),
    CW("CW-169", "python", "Capture stdout for a test", "import sys\nfrom io import StringIO\ndef capture_stdout(fn, *args, **kwargs):\n    buf = StringIO()\n    old = sys.stdout\n    sys.stdout = buf\n    try: fn(*args, **kwargs)\n    finally: sys.stdout = old\n    return buf.getvalue()", "StringIO is a writable file-like object. Saving/restoring sys.stdout in try/finally is robust against exceptions. pytest's capsys fixture is the framework-aware way."),
    CW("CW-170", "python", "Write a Python implementation of GCD", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a", "Euclidean algorithm. Iterative, O(log min(a,b)). For multiple args use functools.reduce(gcd, args) or math.gcd(*args) (3.9+ accepts multiple args)."),
    CW("CW-171", "go", "Apply functional options to a struct constructor", "type Option func(*Server)\nfunc WithTimeout(d time.Duration) Option {\n    return func(s *Server) { s.timeout = d }\n}\nfunc NewServer(opts ...Option) *Server {\n    s := &Server{timeout: 5*time.Second}\n    for _, o := range opts { o(s) }\n    return s\n}", "Each option is a function that mutates the result. Cleaner than long parameter lists; new options don't break the signature."),
    CW("CW-172", "go", "Modify slice elements in place via index range", "for i := range items {\n    items[i] = process(items[i])\n}", "for i, v := range items copies v; for i := range items uses the index for in-place updates. Common gotcha for newcomers used to languages with reference semantics."),
    CW("CW-173", "rust", "Count word frequencies with HashMap entry API", "use std::collections::HashMap;\nfn word_counts(text: &str) -> HashMap<&str, i32> {\n    let mut counts = HashMap::new();\n    for word in text.split_whitespace() {\n        *counts.entry(word).or_insert(0) += 1;\n    }\n    counts\n}", "entry returns OccupiedEntry/VacantEntry. or_insert(0) returns &mut V; *... += 1 mutates in place. One traversal, O(n)."),
    CW("CW-174", "rust", "Iterate a Vec and double each element", "let v = vec![1, 2, 3];\nlet doubled: Vec<i32> = v.iter().map(|x| x * 2).collect();", "iter() borrows; into_iter() takes ownership. collect type comes from the annotation. Iterator chains compile to the same machine code as hand-written loops."),
    CW("CW-175", "javascript", "Build an array of N values via Array.from", "const squares = Array.from({length: 10}, (_, i) => i * i);\n// [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]", "Array.from accepts an iterable OR an array-like ({length: N}). Mapper called with (item, index). Convenient for synthetic ranges without lodash."),
    CW("CW-176", "javascript", "Use a WeakMap for object-keyed memoization", "const cache = new WeakMap();\nfunction memoizeByObject(fn) {\n  return obj => {\n    if (cache.has(obj)) return cache.get(obj);\n    const r = fn(obj);\n    cache.set(obj, r);\n    return r;\n  };\n}", "WeakMap keys are GC-collectable; prevents the memory leak you'd get with Map. Use when keys are arbitrary objects."),
    CW("CW-177", "python", "Read installed package version", "import importlib.metadata as md\ndef package_version(name: str) -> str:\n    return md.version(name)", "Standard library since 3.8. Replaces pkg_resources from setuptools (which is slow + deprecated). md.entry_points reads plugin entry points."),
    CW("CW-178", "python", "Generate isort-friendly atomic temp file path", "import tempfile, os\ndef tmpfile_path(prefix='tmp', suffix='.tmp') -> str:\n    fd, path = tempfile.mkstemp(prefix=prefix, suffix=suffix)\n    os.close(fd)\n    return path", "mkstemp returns an open fd + path. We close the fd because callers will reopen. The file persists; caller is responsible for cleanup. tempfile.mkdtemp creates a temp directory."),
    CW("CW-179", "python", "Compute LCM of multiple integers", "import math\ndef lcm_all(*nums: int) -> int:\n    return math.lcm(*nums)\n# Or for older Python:\nfrom functools import reduce\ndef lcm2(a, b): return a * b // math.gcd(a, b)\ndef lcm_all_old(*nums): return reduce(lcm2, nums)", "math.lcm accepts variadic args in 3.9+. For older Python, fold pairwise with the gcd-based formula."),
    CW("CW-180", "python", "Pack and unpack binary structs", "import struct\ndef pack_record(id_: int, value: float) -> bytes:\n    return struct.pack('>If', id_, value)\ndef unpack_record(blob: bytes) -> tuple:\n    return struct.unpack('>If', blob)", "Format string: '>' big-endian, I = uint32, f = float32. struct.calcsize tells you the byte count. Used for binary protocols, file formats."),
    CW("CW-181", "python", "Make a raw HTTP/1.0 GET via socket", "import socket\ndef raw_get(host, path='/'):\n    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:\n        s.connect((host, 80))\n        s.sendall(f'GET {path} HTTP/1.0\\r\\nHost: {host}\\r\\n\\r\\n'.encode())\n        chunks = []\n        while True:\n            data = s.recv(4096)\n            if not data: break\n            chunks.append(data)\n        return b''.join(chunks)", "Direct TCP. Loop recv until empty (EOF). For HTTPS wrap with ssl.wrap_socket. For real HTTP work use http.client or requests."),
    CW("CW-182", "python", "Strip whitespace + non-ASCII from a string for normalization", "import unicodedata\ndef normalize(s: str) -> str:\n    nfkd = unicodedata.normalize('NFKD', s)\n    return ''.join(c for c in nfkd if not unicodedata.combining(c)).strip()", "NFKD decomposes characters (é -> e + combining accent). combining(c) is True for the accent codepoints. Stripping them gives ASCII-only text. Useful for fuzzy search, slug generation."),
    CW("CW-183", "python", "Capture a subprocess git SHA", "import subprocess\ndef git_sha() -> str:\n    return subprocess.run(\n        ['git', 'rev-parse', 'HEAD'],\n        capture_output=True, text=True, check=True\n    ).stdout.strip()", "argv as list (not string) avoids shell injection. capture_output=True captures stdout+stderr. check=True raises on non-zero exit. text=True decodes UTF-8."),
    CW("CW-184", "python", "Recursively flatten a nested iterable, ignoring strings", "from collections.abc import Iterable\ndef flatten(items):\n    for x in items:\n        if isinstance(x, Iterable) and not isinstance(x, (str, bytes)):\n            yield from flatten(x)\n        else:\n            yield x", "Strings are iterable but you don't want flatten('abc') to yield 'a','b','c'. The exclusion is essential."),
    CW("CW-185", "python", "Read all entries from a zip archive", "import zipfile\ndef zip_entries(path: str) -> dict[str, bytes]:\n    out = {}\n    with zipfile.ZipFile(path) as z:\n        for name in z.namelist():\n            with z.open(name) as f:\n                out[name] = f.read()\n    return out", "ZipFile is a context manager. namelist gives entries; open returns a file-like. For untrusted zips bound max size to prevent zip-bomb attacks."),
    CW("CW-186", "python", "Pretty-print a dict as JSON with stable key order", "import json\ndef pretty(obj) -> str:\n    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False)", "indent=2 for readability. sort_keys for deterministic output (good for diffs / version control). ensure_ascii=False keeps Unicode characters human-readable."),
    CW("CW-187", "python", "Issue a deprecation warning that points at the caller", "import warnings\ndef old_api():\n    warnings.warn(\n        'old_api is deprecated; use new_api',\n        DeprecationWarning, stacklevel=2,\n    )\n    return new_api()", "stacklevel=2 makes the warning point at the caller's line, not yours. DeprecationWarning is hidden by default for most users; UserWarning is shown."),
    CW("CW-188", "python", "Write CSV with all-quoted non-numeric values", "import csv\ndef write_csv(path, rows, header):\n    with open(path, 'w', newline='') as f:\n        w = csv.writer(f, quoting=csv.QUOTE_NONNUMERIC)\n        w.writerow(header)\n        w.writerows(rows)", "newline='' is required (csv handles its own line endings). QUOTE_NONNUMERIC quotes everything except numbers — Excel-friendly."),
    CW("CW-189", "go", "Aggregate multiple errors with errors.Join", "errs := errors.Join(close1(), close2(), close3())\nif errs != nil {\n    return fmt.Errorf(\"cleanup failed: %w\", errs)\n}", "errors.Join (1.20+) returns nil if all inputs are nil; otherwise a multi-error. errors.Is/As walks the joined chain."),
    CW("CW-190", "go", "Run a job with a deadline using context", "ctx, cancel := context.WithDeadline(context.Background(),\n    time.Now().Add(30*time.Second))\ndefer cancel()\nresult := make(chan error, 1)\ngo func() { result <- runJob(ctx) }()\nselect {\ncase err := <-result: return err\ncase <-ctx.Done(): return ctx.Err()\n}", "context.WithDeadline cancels at a wall-clock time. select waits for whichever happens first. Always defer cancel() to release context resources."),
    CW("CW-191", "rust", "Split a Vec at the first element matching a predicate", "fn split_at<T>(v: &[T], pred: impl Fn(&T) -> bool) -> (&[T], &[T]) {\n    let i = v.iter().position(pred).unwrap_or(v.len());\n    v.split_at(i)\n}", "iter().position(pred) returns Option<usize>; unwrap_or(len) means 'split at end' if no match. split_at returns two slices borrowing from v."),
    CW("CW-192", "javascript", "Build a Map from an array of [k, v] pairs", "const map = new Map([['a', 1], ['b', 2]]);\nmap.size                           // 2\nObject.fromEntries(map)             // {a: 1, b: 2}", "Map preserves insertion order, has .size, .has/.get/.set methods. Use Object.fromEntries to convert back to a plain object (for JSON serialisation, etc)."),
    CW("CW-193", "python", "Use Pydantic v2 for typed config validation", "from pydantic import BaseModel, Field\nclass Config(BaseModel):\n    host: str\n    port: int = Field(8080, ge=1, le=65535)\n    workers: int = Field(4, ge=1)\n\ndef load(d: dict) -> Config:\n    return Config.model_validate(d)", "Pydantic v2 validators are written in Rust — fast. model_validate raises ValidationError with structured details on failure. ge/le/gt/lt/min_length/max_length are common constraints."),
    CW("CW-194", "python", "Use functools.cache on a pure function (3.9+)", "import functools\n@functools.cache\ndef expensive(x, y):\n    return slow_computation(x, y)", "functools.cache (3.9+) is unbounded memoization. functools.lru_cache(maxsize=None) does the same. cache.cache_info() reports hits/misses. cache.cache_clear() empties."),
    CW("CW-195", "python", "Use dataclasses with __post_init__ for validation", "from dataclasses import dataclass\n@dataclass\nclass Range:\n    lo: int\n    hi: int\n    def __post_init__(self):\n        if self.lo > self.hi:\n            raise ValueError('lo must be <= hi')", "__post_init__ runs after generated __init__. Useful for cross-field validation. For type-validated dataclasses use Pydantic; standard dataclass + __post_init__ is the lighter alternative."),
]


def _append(bank: Path, patterns: list) -> int:
    if not bank.exists():
        print(f"[error] bank not found: {bank}", file=sys.stderr)
        return 0
    existing = set()
    with bank.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line: continue
            try: existing.add(json.loads(line).get("id"))
            except json.JSONDecodeError: pass
    appended = 0
    with bank.open("a", encoding="utf-8") as f:
        for p in patterns:
            if p["id"] in existing: continue
            f.write(json.dumps(p, ensure_ascii=False) + "\n")
            appended += 1
    return appended


def main() -> int:
    ce = _append(EXPLAIN, EXPLAIN_PATTERNS)
    cw = _append(WRITE, WRITE_PATTERNS)
    print(f"  code-explain: appended {ce}")
    print(f"  code-write:   appended {cw}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
